// Matriz de acceso por rol de TODAS las rutas de staff `/hoteles/:propertyId/*` (H-36).
//
// Es la "verdad de diseno" contra la que `hoteles-guardas-rutas.spec.ts` contrasta la API real:
// - "todos": cualquier rol del staff de la property puede llamarla; el filtrado fino ocurre por
//   fila (RLS: tickets, reservas, lecturas de catalogo) o es lectura de bajo riesgo ya decidida.
// - lista de roles: SOLO esos roles pasan; cualquier otro recibe 403 antes de tocar datos.
// - "por-transicion": el rol permitido depende del par (estado actual, estado destino)
//   (`canRolePerformTransition`); lo cubre `hoteles-reservas.spec.ts`, aqui solo se exige 401/403 de tenant.
//
// Una ruta nueva NO entra sola: el spec falla hasta que se declare aqui su acceso (y por lo tanto
// hasta que alguien decida a proposito que roles la pueden usar). Una ruta borrada tambien falla.
import type { HotelRole } from "@atiende/domain-hoteles";

export type AccesoRuta = "todos" | "por-transicion" | readonly HotelRole[];

export const MATRIZ_GUARDAS: Readonly<Record<string, AccesoRuta>> = {
  "GET /reservas/:reservationId/folios": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "GET /folios/:folioId": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/cargos": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/descuentos": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/cargos/:chargeId/reverso": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/cargos/:chargeId/transferir": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/split": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/pagos": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "POST /folios/:folioId/cerrar": ["owner", "gm", "frontdesk", "reservations", "fnb", "accountant"],
  "GET /chat-datos/estado": ["owner", "gm"],
  "POST /chat-datos": ["owner", "gm"],
  "GET /chat-datos/conversaciones": ["owner", "gm"],
  "GET /chat-datos/conversaciones/:conversationId": ["owner", "gm"],
  "PATCH /chat-datos/conversaciones/:conversationId": ["owner", "gm"],
  "DELETE /chat-datos/conversaciones/:conversationId": ["owner", "gm"],
  "GET /chat-datos/pins": ["owner", "gm"],
  "POST /chat-datos/pins": ["owner", "gm"],
  "PATCH /chat-datos/pins/:pinId": ["owner", "gm"],
  "DELETE /chat-datos/pins/:pinId": ["owner", "gm"],
  "GET /chat-datos/pins/:pinId/resultado": ["owner", "gm"],
  "POST /chat-datos/conversaciones/:conversationId/reporte": ["owner", "gm"],
  "POST /chat-datos/adjuntos": ["owner", "gm"],
  "GET /pedidos-fnb": "todos",
  "POST /pedidos-fnb": ["owner", "gm", "frontdesk", "fnb"],
  "GET /pedidos-fnb/:orderId": "todos",
  "POST /pedidos-fnb/:orderId/confirmar-cocina": ["owner", "gm", "fnb"],
  "POST /pedidos-fnb/:orderId/asegurar-seguridad": ["owner", "gm", "fnb"],
  "POST /quotes": "todos",
  "GET /huespedes/:guestId/ficha": ["owner", "gm", "frontdesk", "reservations"],
  "GET /huespedes/:guestId/exportar-datos": ["owner", "gm"],
  "POST /huespedes/:guestId/notas": ["owner", "gm", "frontdesk", "reservations"],
  "POST /huespedes/:guestId/notas/:noteId/archivar": ["owner", "gm", "frontdesk", "reservations"],
  "GET /recepcion": ["owner", "gm", "frontdesk", "reservations"],
  "POST /recepcion/reservas/:id/check-in": ["owner", "gm", "frontdesk"],
  "POST /recepcion/reservas/:id/check-out": ["owner", "gm", "frontdesk"],
  "POST /recepcion/reservas/:id/cambiar-habitacion": ["owner", "gm", "frontdesk"],
  "GET /reservas": "todos",
  "GET /tipos-habitacion": "todos",
  "GET /huespedes": "todos",
  "POST /huespedes": ["owner", "gm", "frontdesk", "reservations"],
  "GET /reservas/:id": "todos",
  "POST /reservas": ["owner", "gm", "frontdesk", "reservations"],
  "PATCH /reservas/:id/transicion": "por-transicion",
  "POST /reservas/:id/cancelar": ["owner", "gm", "frontdesk", "reservations"],
  "PATCH /reservas/:id/asignar-habitacion": ["owner", "gm", "frontdesk", "reservations"],
  "POST /reservas/:id/fechas/previsualizar": ["owner", "gm", "frontdesk", "reservations"],
  "PATCH /reservas/:id/fechas": ["owner", "gm", "frontdesk", "reservations"],
  "GET /lista-espera": ["owner", "gm", "frontdesk", "reservations"],
  "POST /lista-espera": ["owner", "gm", "frontdesk", "reservations"],
  "POST /lista-espera/:id/cancelar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /lista-espera/:id/ofrecer": ["owner", "gm", "frontdesk", "reservations"],
  "POST /lista-espera/:id/aceptar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /reservas/procesar-no-show": ["owner", "gm"],
  "GET /cfdi": ["owner", "gm", "accountant"],
  "GET /folios/:folioId/cfdi": ["owner", "gm", "accountant"],
  "POST /folios/:folioId/cfdi": ["owner", "gm", "accountant"],
  "POST /folios/:folioId/cfdi/pago": ["owner", "gm", "accountant"],
  "POST /cfdi/:cfdiId/cancelar": ["owner", "gm", "accountant"],
  "POST /cfdi/:cfdiId/consultar-estado": ["owner", "gm", "accountant"],
  "POST /fraude/escaneos": ["owner", "gm", "accountant"],
  "GET /fraude/alertas": ["owner", "gm", "accountant"],
  "GET /fraude/alertas/:alertId": ["owner", "gm", "accountant"],
  "POST /fraude/alertas/:alertId/confirmar": ["owner", "gm", "accountant"],
  "POST /fraude/alertas/:alertId/descartar": ["owner", "gm", "accountant"],
  "POST /night-audit": ["owner", "gm", "accountant"],
  "GET /night-audit/:businessDate": ["owner", "gm", "accountant"],
  "GET /night-audit": ["owner", "gm", "accountant"],
  "POST /mantenimiento/tickets": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "GET /mantenimiento/tickets": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "GET /mantenimiento/tickets/:ticketId": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "POST /mantenimiento/tickets/:ticketId/cerrar": ["owner", "gm", "maintenance"],
  "POST /housekeeping/turnos": ["owner", "gm", "frontdesk"],
  "GET /housekeeping/turnos": "todos",
  "GET /housekeeping/tablero": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "GET /housekeeping/reporte": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "GET /housekeeping/camaristas": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "GET /housekeeping/tareas": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "POST /housekeeping/tareas/generar": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/tareas": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/tareas/:taskId/iniciar": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/tareas/:taskId/terminar": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/tareas/:taskId/inspeccionar": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/tareas/:taskId/asignar": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/tareas/:taskId/cancelar": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/habitaciones/:roomId/sucia": ["owner", "gm", "frontdesk", "housekeeping"],
  "GET /housekeeping/fuera-de-servicio": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "POST /housekeeping/fuera-de-servicio": ["owner", "gm", "frontdesk", "maintenance"],
  "POST /housekeeping/fuera-de-servicio/:id/rehabilitar": ["owner", "gm", "frontdesk", "maintenance"],
  // H-26 (migracion 039): housekeeping residual. Espejo de can_configure_property (config: owner/gm) y can_work_housekeeping (fotos, blancos, opt-out).
  "GET /housekeeping/configuracion": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "PUT /housekeeping/configuracion": ["owner", "gm"],
  "POST /housekeeping/asignacion-automatica": ["owner", "gm", "frontdesk"],
  "GET /housekeeping/tareas/:taskId/fotos": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "POST /housekeeping/tareas/:taskId/fotos": ["owner", "gm", "frontdesk", "housekeeping"],
  "GET /housekeeping/tareas/:taskId/fotos/:photoId": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "DELETE /housekeeping/tareas/:taskId/fotos/:photoId": ["owner", "gm", "frontdesk", "housekeeping"],
  "GET /housekeeping/blancos": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "PUT /housekeeping/blancos": ["owner", "gm", "frontdesk", "housekeeping"],
  "GET /housekeeping/opt-out": ["owner", "gm", "frontdesk", "housekeeping", "maintenance"],
  "POST /housekeeping/opt-out": ["owner", "gm", "frontdesk", "housekeeping"],
  "POST /housekeeping/opt-out/:id/revertir": ["owner", "gm", "frontdesk", "housekeeping"],
  // H-29 (migracion 039): canal WhatsApp y agente de voz. owner/gm (can_configure_property); el secreto de voz es write-only.
  "GET /mensajeria": ["owner", "gm"],
  "PUT /mensajeria/whatsapp": ["owner", "gm"],
  "PUT /mensajeria/voz": ["owner", "gm"],
  "POST /mensajeria/voz/rotar-secreto": ["owner", "gm"],
  "POST /asistencia/checar": "todos",
  "GET /asistencia": "todos",
  "POST /asistencia/horarios": ["owner", "gm"],
  "GET /asistencia/cruce": ["owner", "gm"],
  "GET /asistencia/exportar-stps": ["owner", "gm"],
  "GET /pl": ["owner", "gm", "accountant"],
  "POST /pl/gastos": ["owner", "gm", "accountant"],
  "GET /pl/gastos": ["owner", "gm", "accountant"],
  "POST /tipos-habitacion": ["owner", "gm"],
  "GET /habitaciones": "todos",
  "POST /tipos-habitacion/:roomTypeId/habitaciones": ["owner", "gm"],
  "POST /tarifas": ["owner", "gm"],
  "GET /tarifas": ["owner", "gm", "accountant"],
  "PUT /tarifas/:rateId": ["owner", "gm"],
  "GET /configuracion/impuestos": ["owner", "gm", "accountant"],
  "PUT /configuracion/impuestos": ["owner", "gm"],
  "GET /configuracion/politica-cancelacion": ["owner", "gm", "accountant"],
  "PUT /configuracion/politica-cancelacion": ["owner", "gm"],
  "GET /configuracion/sobreventa": ["owner", "gm", "accountant"],
  "PUT /configuracion/sobreventa/:roomTypeId": ["owner", "gm"],
  "GET /configuracion/bitacora": ["owner", "gm"],
  "GET /primeros-pasos": ["owner", "gm"],
  "POST /primeros-pasos/omitir": ["owner", "gm"],
  "GET /configuracion": "todos",
  "PUT /configuracion": ["owner", "gm"],
  "GET /revenue/gate": "todos",
  "POST /revenue/gate": ["owner", "gm"],
  "POST /revenue/gate/transicion": ["owner", "gm"],
  "POST /revenue/gate/aprobacion-autopilot": ["owner"],
  "GET /revenue/backtests": "todos",
  "POST /revenue/backtests": ["owner", "gm", "accountant"],
  "POST /revenue/explicacion-precio": ["owner", "gm"],
  "POST /revenue/verificacion-paridad": ["owner", "gm"],
  "POST /revenue/compset/verificacion": ["owner", "gm"],
  "GET /revenue/recomendaciones": "todos",
  "GET /revenue/recomendaciones/:id": "todos",
  "POST /revenue/recomendaciones/:id/aprobar": ["owner", "gm"],
  "POST /revenue/recomendaciones/:id/descartar": ["owner", "gm"],
  "GET /revenue/pricing-rule/:roomTypeId": "todos",
  "PUT /revenue/pricing-rule/:roomTypeId": ["owner", "gm"],
  "GET /revenue/local-events": "todos",
  "POST /revenue/local-events": ["owner", "gm", "accountant"],
  "GET /revenue/competitor-rates": "todos",
  "POST /revenue/competitor-rates": ["owner", "gm", "accountant"],
  "POST /reputacion/resenas": ["owner", "gm", "frontdesk", "reservations"],
  "GET /reputacion/resenas": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "GET /reputacion/resenas/:reviewId": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /reputacion/resenas/:reviewId/respuestas": ["owner", "gm", "frontdesk", "reservations"],
  "GET /reputacion/resenas/:reviewId/respuestas": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /reputacion/acciones/:actionId/resolver": ["owner", "gm", "accountant"],
  "GET /reputacion/indice": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "GET /identidad": ["owner", "gm", "frontdesk", "reservations"],
  "POST /identidad": ["owner", "gm", "frontdesk", "reservations"],
  "POST /identidad/:identidadId/verificar": ["owner", "gm", "frontdesk"],
  "POST /identidad/:identidadId/revelar": ["owner", "gm", "frontdesk"],
  "GET /identidad/:identidadId/accesos": ["owner", "gm"],
  "POST /identidad/:identidadId/solicitar-purga": ["owner", "gm"],
  "GET /identidad-purgas": ["owner", "gm"],
  "POST /identidad-purgas/:solicitudId/decidir": ["owner", "gm"],
  "GET /registro-migratorio": ["owner", "gm", "frontdesk", "reservations"],
  "POST /registro-migratorio": ["owner", "gm", "frontdesk", "reservations"],
  "POST /registro-migratorio/:registroId/reportar": ["owner", "gm", "frontdesk", "reservations"],
  "GET /privacidad/info": ["owner", "gm", "frontdesk", "reservations"],
  "GET /privacidad/configuracion": ["owner", "gm"],
  "PUT /privacidad/configuracion": ["owner", "gm"],
  "GET /privacidad/avisos": ["owner", "gm", "frontdesk", "reservations"],
  "POST /privacidad/avisos": ["owner", "gm"],
  "GET /privacidad/consentimientos": ["owner", "gm", "frontdesk", "reservations"],
  "POST /privacidad/consentimientos": ["owner", "gm", "frontdesk", "reservations"],
  "POST /privacidad/consentimientos/:consentimientoId/revocar": ["owner", "gm", "frontdesk", "reservations"],
  "GET /privacidad/arco": ["owner", "gm"],
  "POST /privacidad/arco": ["owner", "gm"],
  "POST /privacidad/arco/:solicitudId/avanzar": ["owner", "gm"],
  "POST /privacidad/arco/:solicitudId/prorroga": ["owner", "gm"],
  "POST /privacidad/arco/:solicitudId/enlace-mis-datos": ["owner", "gm"],
  "GET /privacidad/incidentes": ["owner", "gm"],
  "POST /privacidad/incidentes": ["owner", "gm", "frontdesk", "reservations"],
  "POST /privacidad/incidentes/:incidenteId/accion": ["owner", "gm"],
  "POST /privacidad/identidades/:identidadId/bloquear": ["owner", "gm"],
  "GET /privacidad/retenciones": ["owner", "gm"],
  "POST /privacidad/identidades/:identidadId/retencion": ["owner", "gm"],
  "POST /privacidad/retenciones/:retencionId/liberar": ["owner", "gm"],
  "POST /privacidad/identidades/:identidadId/acceso-excepcional": ["owner", "gm"],
  "GET /privacidad/accesos-excepcionales": ["owner", "gm"],
  "POST /privacidad/accesos-excepcionales/:solicitudId/decidir": ["owner", "gm"],
  "POST /privacidad/accesos-excepcionales/:solicitudId/revelar": ["owner", "gm"],
  "GET /privacidad/bitacora": ["owner", "gm"],
  "GET /tickets": "todos",
  "POST /tickets": "todos",
  "GET /tickets/sla": "todos",
  "PUT /tickets/sla": ["owner", "gm"],
  "GET /tickets/resenas-pendientes": ["owner", "gm", "frontdesk", "reservations"],
  "POST /tickets/desde-resena": ["owner", "gm", "frontdesk", "reservations"],
  "GET /tickets/:ticketId": "todos",
  "POST /tickets/:ticketId/iniciar": "todos",
  "POST /tickets/:ticketId/cerrar": "todos",
  "POST /tickets/:ticketId/cancelar": "todos",
  "POST /tickets/:ticketId/escalar": ["owner", "gm", "frontdesk"],
  "POST /tickets/:ticketId/asignar": "todos",
  "POST /tickets/:ticketId/reasignar": ["owner", "gm", "frontdesk"],
  "GET /agentes": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "GET /agentes/guardrails": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "PUT /agentes/guardrails": ["owner", "gm"],
  "GET /agentes/politicas": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "PUT /agentes/politicas/:accion": ["owner", "gm"],
  "GET /agentes/plantillas": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /agentes/plantillas": ["owner", "gm", "frontdesk", "reservations"],
  "POST /agentes/plantillas/:id/enviar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /agentes/plantillas/:id/aprobar": ["owner", "gm"],
  "POST /agentes/plantillas/:id/rechazar": ["owner", "gm"],
  "POST /agentes/plantillas/:id/archivar": ["owner", "gm"],
  "PUT /agentes/:agentKey": ["owner", "gm"],
  "GET /aprobaciones": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /aprobaciones": ["owner", "gm", "frontdesk", "reservations"],
  "GET /aprobaciones/:id": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /aprobaciones/:id/aprobar": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /aprobaciones/:id/rechazar": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /aprobaciones/:id/cancelar": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /aprobaciones/:id/ejecutar": ["owner", "gm"],
  "GET /grupos/cotizaciones": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /grupos/cotizaciones": ["owner", "gm", "reservations"],
  "GET /grupos/cotizaciones/:id": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /grupos/cotizaciones/:id/enviar": ["owner", "gm", "reservations"],
  "POST /grupos/cotizaciones/:id/cerrar": ["owner", "gm", "reservations"],
  "POST /grupos/cotizaciones/:id/aceptar": ["owner", "gm", "reservations"],
  "POST /grupos/cotizaciones/:id/anticipos": ["owner", "gm", "accountant"],
  "GET /grupos/bloqueos": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "GET /grupos/bloqueos/:id": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /grupos/bloqueos/:id/huespedes": ["owner", "gm", "frontdesk", "reservations"],
  "POST /grupos/huespedes/:entryId/confirmar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /grupos/huespedes/:entryId/cancelar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /grupos/bloqueos/:id/liberar": ["owner", "gm", "reservations"],
  "POST /grupos/bloqueos/:id/cancelar": ["owner", "gm", "reservations"],
  "GET /reservas-agente/holds": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "POST /reservas-agente/holds/:holdId/decidir": ["owner", "gm", "reservations"],
  "POST /reservas-agente/holds/:holdId/link-pago": ["owner", "gm", "reservations"],
  "POST /reservas-agente/holds/:holdId/confirmar": ["owner", "gm", "reservations"],
  "POST /reservas-agente/holds/:holdId/cancelar": ["owner", "gm", "reservations"],
  "GET /reservas-agente/politica": ["owner", "gm", "frontdesk", "reservations", "accountant"],
  "PUT /reservas-agente/politica": ["owner", "gm"],
  "POST /voz/config": ["owner", "gm"],
  // Voz sobre voice-core: estado honesto de la escalera y sesion de vista previa. owner/gm (ADMIN_ROLES); no llevan secretos.
  "GET /voz/estado": ["owner", "gm"],
  "POST /voz/preview/sesion": ["owner", "gm"],
  "GET /conversaciones": ["owner", "gm", "frontdesk", "reservations"],
  "GET /conversaciones/:id": ["owner", "gm", "frontdesk", "reservations"],
  "POST /conversaciones/:id/leer": ["owner", "gm", "frontdesk", "reservations"],
  "POST /conversaciones/:id/tomar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /conversaciones/:id/devolver-al-agente": ["owner", "gm", "frontdesk", "reservations"],
  "POST /conversaciones/:id/cerrar": ["owner", "gm", "frontdesk", "reservations"],
  "POST /conversaciones/:id/notas": ["owner", "gm", "frontdesk", "reservations"],
  "POST /conversaciones/:id/responder": ["owner", "gm", "frontdesk", "reservations"],
};
