// Fixture INLINE derivado de work/base-vieja-pm/colonias.json (colonias del piloto original, ninguna con coordenadas): nombre, sucursal mas cercana y 2.a con sus km.
// Una fila por colonia unica (sin acentos). No depende de ningun archivo fuera del repo.
export type FilaColoniaPiloto = readonly [colonia: string, ref1: string, km1: number | null, ref2: string | null, km2: number | null];
export const COLONIAS_PILOTO: readonly FilaColoniaPiloto[] = [
  ["alcala martin", "prol-montejo", 2.6, "pensiones", 2.9],
  ["aleman", "prol-montejo", 2.5, "garcia-lavin", 4.6],
  ["algarrobos residencial", "garcia-lavin", 2.5, "altabrisa", 3.3],
  ["altabrisa", "altabrisa", 1.1, "garcia-lavin", 2.4],
  ["andalucia", "galerias", 2.2, "garcia-lavin", 3.5],
  ["andria", "altabrisa", 4.1, "garcia-lavin", 7.4],
  ["arboledas", "prol-montejo", 3.5, "pensiones", 4.7],
  ["aurea residencial", "galerias", 0.5, "fco-montejo", 1.7],
  ["azcorra", "pensiones", 6.6, "prol-montejo", 6.8],
  ["benito juarez norte", "garcia-lavin", 1.3, "prol-montejo", 1.4],
  ["benito juarez oriente", "prol-montejo", 7.5, "altabrisa", 7.8],
  ["bojorquez", "pensiones", 1.6, "prol-montejo", 5.5],
  ["buenavista", "pensiones", 1.3, "prol-montejo", 3.2],
  ["camara de comercio norte", "altabrisa", 1.9, "prol-montejo", 2.3],
  ["campestre", "prol-montejo", 0.6, "garcia-lavin", 2.6],
  ["caucel", "pensiones", 1.8, "fco-montejo", 4.8],
  ["cecilio chi", "pensiones", 9.5, "prol-montejo", 10.0],
  ["ceiba ii", "galerias", 7.9, "garcia-lavin", 8.0],
  ["centro", "pensiones", 3.8, "prol-montejo", 5.1],
  ["centro chichi suarez", "altabrisa", 4.1, "prol-montejo", 6.7],
  ["centro historico", "pensiones", 3.8, "prol-montejo", 5.0],
  ["cerrada lombardia", "altabrisa", 3.8, "garcia-lavin", 7.1],
  ["cerrada piemonte", "altabrisa", 3.7, "garcia-lavin", 7.0],
  ["cerrada veneto", "altabrisa", 4.0, "garcia-lavin", 7.3],
  ["cerradas de gran santa fe", "fco-montejo", 4.8, "pensiones", 4.9],
  ["chablekal", "altabrisa", 7.8, "garcia-lavin", 7.8],
  ["chichi suarez", "altabrisa", 3.8, "prol-montejo", 6.0],
  ["chicxulub", "playa", 0.6, "galerias", 28.7],
  ["chicxulub puerto", "playa", 0.6, "galerias", 28.7],
  ["cholul", "altabrisa", 2.6, "garcia-lavin", 4.5],
  ["chuburna", "fco-montejo", 2.0, "pensiones", 2.0],
  ["chuminopolis", "pensiones", 3.1, "fco-montejo", 6.8],
  ["ciudad caucel", "pensiones", 1.8, "fco-montejo", 4.8],
  ["cloverleaf", "altabrisa", 3.0, "garcia-lavin", 6.1],
  ["del norte", "prol-montejo", 1.0, "garcia-lavin", 2.9],
  ["delio moreno canton", "pensiones", 5.8, "prol-montejo", 8.1],
  ["dolores otero", "pensiones", 6.2, "prol-montejo", 7.9],
  ["dzitya", "galerias", 3.9, "fco-montejo", 4.7],
  ["dzitya poligono chuburna", "galerias", 1.7, "fco-montejo", 3.0],
  ["el fenix", "prol-montejo", 3.7, "pensiones", 5.0],
  ["emiliano zapata norte", "garcia-lavin", 0.6, "prol-montejo", 1.8],
  ["ferrocarrilera hector victoria aguilar", "prol-montejo", 3.5, "pensiones", 4.2],
  ["floresta residencial", "altabrisa", 2.9, "garcia-lavin", 6.1],
  ["fraccionamiento francisco de montejo", "garcia-lavin", 0.4, "prol-montejo", 2.7],
  ["francisco de montejo", "garcia-lavin", 0.4, "prol-montejo", 2.7],
  ["galerias", "galerias", 0.6, "fco-montejo", 1.6],
  ["garcia gineres", "pensiones", 3.0, "prol-montejo", 5.1],
  ["gonzalo guerrero", "prol-montejo", 1.9, "galerias", 1.9],
  ["gran herradura norte", "pensiones", 5.4, "fco-montejo", 7.2],
  ["gran santa fe", "pensiones", 4.0, "fco-montejo", 4.4],
  ["gran santa fe ii", "fco-montejo", 4.4, "pensiones", 5.0],
  ["guadalupe", "prol-montejo", 1.3, "garcia-lavin", 3.7],
  ["hacienda xcumpich", "fco-montejo", 1.0, "galerias", 1.1],
  ["inalambrica", "pensiones", 1.3, "prol-montejo", 4.6],
  ["itzimna", "pensiones", 2.7, "prol-montejo", 3.3],
  ["jardines de merida", "pensiones", 5.4, "prol-montejo", 9.0],
  ["jardines de miraflores", "prol-montejo", 5.7, "pensiones", 6.2],
  ["jardines de vista alegre i", "altabrisa", 2.0, "prol-montejo", 3.0],
  ["jardines de vista alegre ii", "altabrisa", 1.9, "prol-montejo", 3.3],
  ["jesus carranza", "prol-montejo", 2.9, "pensiones", 4.4],
  ["juan pablo ii", "pensiones", 4.1, "fco-montejo", 7.7],
  ["komchen", "galerias", 6.3, "fco-montejo", 7.1],
  ["la castellana", "galerias", 0.5, "fco-montejo", 2.0],
  ["la ceiba", "pensiones", 5.9, "prol-montejo", 8.3],
  ["la ciudadela", "pensiones", 3.9, "fco-montejo", 5.2],
  ["la huerta", "prol-montejo", 3.2, "pensiones", 3.9],
  ["las americas", "galerias", 4.1, "fco-montejo", 4.7],
  ["las americas ii", "galerias", 5.3, "fco-montejo", 6.0],
  ["las americas merida", "galerias", 4.1, "fco-montejo", 4.7],
  ["leandro valle", "altabrisa", 3.8, "prol-montejo", 5.4],
  ["lomas del sur", "pensiones", 5.1, "prol-montejo", 8.2],
  ["los heroes", "altabrisa", 5.9, "prol-montejo", 8.5],
  ["los reyes", "pensiones", 4.6, "prol-montejo", 7.5],
  ["lourdes", "pensiones", 5.5, "prol-montejo", 5.7],
  ["lourdes industrial", "prol-montejo", 3.9, "pensiones", 4.6],
  ["mallorca", "altabrisa", 2.4, "garcia-lavin", 5.6],
  ["manzana 115", "pensiones", 5.2, "prol-montejo", 8.0],
  ["maximo ancona", "prol-montejo", 3.8, "pensiones", 5.3],
  ["meliton salazar", "pensiones", 5.5, "prol-montejo", 8.1],
  ["mexico", "prol-montejo", 1.1, "garcia-lavin", 3.3],
  ["mexico norte", "pensiones", 1.5, "prol-montejo", 3.1],
  ["mexico oriente", "prol-montejo", 1.1, "garcia-lavin", 3.3],
  ["mexico poniente", "pensiones", 0.5, "prol-montejo", 4.2],
  ["miguel hidalgo", "pensiones", 3.6, "prol-montejo", 7.0],
  ["miraflores", "prol-montejo", 6.7, "pensiones", 7.2],
  ["montealban", "prol-montejo", 1.4, "garcia-lavin", 1.5],
  ["montebello", "altabrisa", 2.4, "prol-montejo", 3.9],
  ["montebello ii", "altabrisa", 1.4, "garcia-lavin", 1.9],
  ["montecarlo", "altabrisa", 0.7, "garcia-lavin", 2.6],
  ["montecristo", "prol-montejo", 1.7, "garcia-lavin", 2.2],
  ["montereal", "garcia-lavin", 1.6, "prol-montejo", 1.7],
  ["montes de ame", "garcia-lavin", 1.1, "galerias", 1.7],
  ["montevideo", "altabrisa", 2.0, "prol-montejo", 2.3],
  ["morelos oriente", "prol-montejo", 7.4, "pensiones", 7.5],
  ["mulchechen", "pensiones", 8.6, "prol-montejo", 8.8],
  ["mulsay", "altabrisa", 1.0, "garcia-lavin", 2.4],
  ["nucleo sodzil", "galerias", 1.8, "garcia-lavin", 3.4],
  ["nueva aleman", "prol-montejo", 2.5, "garcia-lavin", 4.6],
  ["nueva reforma agraria", "pensiones", 5.6, "fco-montejo", 9.0],
  ["nueva salvador alvarado sur", "pensiones", 8.5, "prol-montejo", 8.7],
  ["nuevo yucatan", "altabrisa", 3.2, "prol-montejo", 3.4],
  ["obrera", "pensiones", 5.0, "prol-montejo", 7.9],
  ["olivos", "altabrisa", 5.2, "garcia-lavin", 8.0],
  ["opichen", "pensiones", 5.7, "fco-montejo", 9.3],
  ["paraiso santa fe", "fco-montejo", 4.1, "pensiones", 4.1],
  ["parque central", "altabrisa", 3.6, "garcia-lavin", 6.8],
  ["parque industrial", "galerias", 3.5, "fco-montejo", 4.8],
  ["parque natura", "altabrisa", 3.4, "garcia-lavin", 6.6],
  ["pedregales de circuito", "pensiones", 5.7, "prol-montejo", 8.6],
  ["pedregales las americas", "galerias", 4.5, "fco-montejo", 4.7],
  ["pensiones", "pensiones", 2.4, "prol-montejo", 4.0],
  ["piedrasul", "galerias", 1.0, "fco-montejo", 1.2],
  ["plan de ayala", "prol-montejo", 1.4, "garcia-lavin", 2.3],
  ["privada del carmen", "pensiones", 1.7, "prol-montejo", 5.1],
  ["privada las acacias", "altabrisa", 4.4, "prol-montejo", 7.4],
  ["progreso", "playa", 6.3, "galerias", 27.4],
  ["puerta de piedra dzitya", "fco-montejo", 2.5, "galerias", 3.3],
  ["punta esmeralda", "altabrisa", 5.2, "prol-montejo", 7.0],
  ["quinta real", "galerias", 6.8, "garcia-lavin", 7.8],
  ["real de dzitya", "fco-montejo", 3.6, "galerias", 4.1],
  ["real montejo", "fco-montejo", 2.6, "galerias", 4.1],
  ["real san jose", "prol-montejo", 7.3, "pensiones", 7.9],
  ["reparto dolores patron peniche", "pensiones", 2.5, "prol-montejo", 2.8],
  ["residencial pensiones", "pensiones", 2.4, "prol-montejo", 4.0],
  ["residencial san antonio", "garcia-lavin", 1.3, "prol-montejo", 1.7],
  ["revolucion", "galerias", 0.5, "garcia-lavin", 2.3],
  ["revolucion cordemex", "galerias", 0.0, "fco-montejo", 2.1],
  ["rinconada de chuburna", "fco-montejo", 1.6, "galerias", 2.0],
  ["roble agricola", "pensiones", 9.3, "prol-montejo", 13.0],
  ["royal del parque", "galerias", 2.5, "fco-montejo", 3.8],
  ["salvador alvarado sur", "pensiones", 8.2, "prol-montejo", 8.6],
  ["sambula", "pensiones", 4.1, "prol-montejo", 7.4],
  ["san angel", "altabrisa", 4.6, "prol-montejo", 6.1],
  ["san antonio cinta", "prol-montejo", 0.9, "garcia-lavin", 2.3],
  ["san antonio cucul", "garcia-lavin", 1.1, "prol-montejo", 1.4],
  ["san antonio xluch", "pensiones", 8.3, "prol-montejo", 10.7],
  ["san aroldo", "pensiones", 9.6, "prol-montejo", 9.9],
  ["san diego cutz", "altabrisa", 6.8, "garcia-lavin", 7.6],
  ["san esteban", "prol-montejo", 2.6, "altabrisa", 3.9],
  ["san jose", "pensiones", 6.4, "prol-montejo", 7.1],
  ["san jose tzal", "pensiones", 9.0, "prol-montejo", 9.3],
  ["san jose vergel", "prol-montejo", 6.9, "pensiones", 7.6],
  ["san lorenzo", "pensiones", 2.6, "prol-montejo", 6.2],
  ["san luis", "prol-montejo", 3.5, "pensiones", 5.1],
  ["san pedro cholul", "altabrisa", 2.8, "garcia-lavin", 6.1],
  ["san pedro noh pat", "altabrisa", 8.8, "prol-montejo", 9.1],
  ["san ramon", "prol-montejo", 1.0, "garcia-lavin", 1.4],
  ["san ramon norte", "prol-montejo", 1.0, "garcia-lavin", 1.5],
  ["santa cecilia", "prol-montejo", 3.4, "pensiones", 3.9],
  ["santa gertrudis", "garcia-lavin", 1.3, "altabrisa", 3.2],
  ["santa gertrudis copo", "prol-montejo", 1.3, "garcia-lavin", 3.6],
  ["santa maria chi", "altabrisa", 3.2, "prol-montejo", 5.7],
  ["santa maria de guadalupe", "pensiones", 4.9, "prol-montejo", 7.8],
  ["santa rosa", "pensiones", 5.6, "prol-montejo", 6.9],
  ["serapio rendon", "pensiones", 7.5, "prol-montejo", 8.9],
  ["sitpach", "altabrisa", 5.7, "garcia-lavin", 9.0],
  ["sodzil", "galerias", 1.1, "garcia-lavin", 1.7],
  ["sodzil norte", "galerias", 1.1, "garcia-lavin", 2.0],
  ["sol campestre", "garcia-lavin", 1.1, "prol-montejo", 1.7],
  ["susula", "pensiones", 5.4, "fco-montejo", 7.9],
  ["tamarindos", "fco-montejo", 2.3, "galerias", 2.4],
  ["tecnologico", "prol-montejo", 1.1, "garcia-lavin", 2.9],
  ["temozon norte", "garcia-lavin", 1.7, "altabrisa", 1.8],
  ["tixcuytun", "altabrisa", 4.8, "garcia-lavin", 5.6],
  ["vergel", "prol-montejo", 6.2, "pensiones", 7.1],
  ["vergel ii", "prol-montejo", 7.1, "pensiones", 8.0],
  ["via montejo", "galerias", 0.6, "fco-montejo", 2.5],
  ["vicente solis", "pensiones", 6.4, "prol-montejo", 6.8],
  ["villa fontana", "prol-montejo", 4.4, "pensiones", 4.8],
  ["villa magna", "pensiones", 5.1, "fco-montejo", 8.6],
  ["villareal", "garcia-lavin", 0.5, "prol-montejo", 2.8],
  ["villas cholul", "altabrisa", 4.2, "garcia-lavin", 7.1],
  ["villas del rey", "prol-montejo", 0.9, "garcia-lavin", 1.8],
  ["villas la hacienda", "prol-montejo", 0.8, "garcia-lavin", 1.5],
  ["vista alegre", "prol-montejo", 1.5, "garcia-lavin", 2.0],
  ["vista alegre norte", "altabrisa", 0.0, "garcia-lavin", 3.3],
  ["waspa", "prol-montejo", 4.7, "pensiones", 5.1],
  ["xaman kab", "garcia-lavin", 0.3, "prol-montejo", 2.6],
  ["xaman tan", "garcia-lavin", 0.5, "prol-montejo", 2.6],
  ["xcanatun", "galerias", 4.0, "garcia-lavin", 5.4],
  ["xcumpich", "altabrisa", 1.1, "garcia-lavin", 2.8],
  ["xo tik", "galerias", 2.6, "fco-montejo", 3.6],
  ["yucalpeten", "pensiones", 1.8, "fco-montejo", 5.4],
  ["yucatan", "pensiones", 2.4, "prol-montejo", 4.7],
];
