// Corpus etiquetado de ARCO para PM (recall primero). true = es una solicitud de derechos (request / menu / third_party; NUNCA null); false = no es ARCO.
// Las 112 primeras vienen de la revision independiente de #528; el resto es propio (jerga mexicana, mayusculas, sin acentos, pronombres pegados, "en su sistema").
export const CORPUS_ARCO: ReadonlyArray<readonly [string, boolean, string?]> = [
 // obligatorias ARCO
 ["ya les di mis datos y quiero que los borren", true],
 ["borren mis datos de mi pedido, ya no quiero que los tengan", true],
 ["quiero eliminar mis datos, ya no voy a hacer otro pedido", true],
 ["ya les pasé mis datos, quiero darme de baja", true],
 ["borren mis datos y facturame", true],
 ["cancelen mis datos", true],
 ["me opongo a que usen mis datos para mi pedido", true],
 // obligatorias NO
 ["ya te pasé mis datos, facturame", false],
 ["necesito factura, mis datos son Juan Perez RFC PEJU800101XXX", false],
 // corpus propio ARCO
 ["BORREN MIS DATOS PORFAVOR", true],
 ["k borren mis datos", true],
 ["kiero que borren mis datos ya", true],
 ["ya no quiero que tengan mis datos", true],
 ["eliminen mis datos personales de su sistema", true],
 ["quiero ejercer mis derechos arco", true],
 ["no quiero que usen mis datos para publicidad", true],
 ["dejen de usar mis datos, ya les pedi una orden y me llegan mensajes", true],
 ["dejen de mandarme promociones, no autorizo el uso de mis datos", true],
 ["quiero saber que datos tienen mios", true],
 ["que datos personales tienen de mi?", true],
 ["quiero una copia de mis datos personales", true],
 ["mis datos estan mal, corrijan mi nombre", true],
 ["actualicen mis datos, cambie de correo", true],
 ["ya les di mis datos en el pedido pasado pero estan mal, corrijanlos", true],
 ["den de baja mis datos", true],
 ["denme de baja de su base de datos", true],
 ["sáquenme de su base de datos", true],
 ["quiero que borren mi numero y mi direccion de su sistema", true],
 ["no quiero que guarden mis datos", true],
 ["ya no me manden nada y borren mi info", true],
 ["olviden mis datos", true],
 ["revoco mi consentimiento para que usen mis datos", true],
 ["ya te pase mis datos, ahora borralos", true],
 ["borra mis datos, ya no voy a pedir", true],
 ["quiero que eliminen mis datos despues de entregar mi pedido", true],
 ["ya les mande mis datos para la factura pero quiero que los borren despues", true],
 ["ya les di mis datos y no quiero que los compartan con nadie", true],
 ["por favor eliminar mis datos del aviso de privacidad", true],
 ["k datos mios tienen? kiero verlos", true],
 ["qué hacen con mis datos?", true],
 ["quiero ver mis datos, ya les hice un pedido", true],
 ["quiero saber que hacen con mis datos de mi pedido", true],
 ["mandenme mis datos que tienen guardados, hice una orden la semana pasada", true],
 // NO ARCO (falsos positivos potenciales)
 ["mi direccion es calle 60 x 45 centro, borren la salsa de mi pedido", false],
 ["cancelen mi pedido", false],
 ["datos de mi tarjeta no, solo efectivo", false],
 ["quiero cancelar mi orden", false],
 ["ya te mande mis datos, cuando llega mi pedido", false],
 ["te pase mis datos para el pedido, ¿ya lo vieron?", false],
 ["mis datos de facturacion: RFC XAXX010101000, correo a@b.com", false],
 ["actualiza mi direccion de entrega", false],
 ["ya les pase mis datos, me mandan el ticket", false],
 ["mis datos son: Juan, calle 20 #300, quiero 1 kilo de cochinita", false],
 ["ya te di mis datos, quiero ver el estado de mi orden", false],
 ["ya les di mis datos, cancelen el pedido porfa ya no lo quiero", false],
 ["te pase mis datos, cancela la orden y haz otra", false],
 ["cancelar pedido, ya les mande mis datos", false],
 ["corrijan mi pedido, ya les pase mis datos, era sin cebolla", false],
 ["ya te pase mis datos, quiero modificar la orden", false],
 ["quiero factura, mis datos son los mismos de la vez pasada", false],
 ["envien la factura con mis datos", false],
 ["borren la cebolla, mis datos ya los tienen", false],
 // ===== NUEVOS adversariales (vuelta 3) ARCO =====
 ["mis datos del pedido: bórrenme por favor", true, "N"],
 ["ya les pase mis datos, eliminenme", true, "N"],
 ["ya le di mis datos, cancelenlos", true, "N"],
 ["YA LES PASE MIS DATOS Y NO QUIERO Q LOS TENGAN", true, "N"],
 ["ya les pase mis datos x el pedido, kiero k los borren", true, "N"],
 ["ya les di mis datos, que me borren", true, "N"],
 ["ya les pase mis datos en el pedido, quiero que me borren de su lista", true, "N"],
 ["ya les di mis datos en el pedido, ya no los quiero ahi, quitenlos", true, "N"],
 ["con mi pedido les di mis datos, ya no los quiero en su sistema", true, "N"],
 ["ya les pase mis datos, quiero saber que tienen de mi", true, "N"],
 ["ya te pase mis datos, ya no quiero que me manden promos con ellos", true, "N"],
 ["ya les di mis datos, borren todo", true, "N"],
 ["ya les pase mis datos con la factura, ya no los quiero en su sistema", true, "N"],
 ["ya les di mis datos, no quiero aparecer en su sistema", true, "N"],
 ["mi tarjeta y mis datos los di en el pedido, eliminen todo eso", true, "N"],
 ["q borren mis datos xfa", true, "N"],
 ["BORREN TODOS MIS DATOS YA", true, "N"],
 ["porfa ya borren mis datos, tengo una queja", true, "N"],
 ["quiero que borren mis datos de la tarjeta", true, "N"],
 ["borrenme mis datos", true, "N"],
 ["mis datos los quiero borrados", true, "N"],
 ["ya, mis datos los quiero fuera de su sistema", true, "N"],
 ["ya les pase mis datos para la factura, ahora eliminenlos", true, "N"],
 ["pasenme mis datos q tienen, hice pedido ayer", true, "N"],
 ["Corrijan mis datos, mi tel esta mal en el pedido", true, "N"],
 ["ya cancelen todo, mis datos tambien", true, "N"],
 ["no autorizo que compartan mis datos con terceros", true, "N"],
 ["BORRA MIS DATOS Y CANCELA MI PEDIDO", true, "N"],
 ["ya les di mis datos de mi direccion y telefono en la orden, olvidenlos", true, "N"],
 ["mi queja: ya les pase mis datos y me llega spam, ya no los usen", true, "N"],
 // ===== NUEVOS adversariales NO ARCO =====
 ["estos son mis datos: Juan Perez, calle 50 #200, quiero 3 tacos de cochinita", false, "N"],
 ["mis datos de contacto son 9991234567, mandame 2 kilos de cochinita", false, "N"],
 ["aqui van mis datos para el envio: calle 60 #500 centro", false, "N"],
 ["te mando mis datos: Maria Lopez 9999876543", false, "N"],
 ["mis datos: Pedro, cel 9991112233, para recoger a las 3", false, "N"],
 ["cancelen el pedido, mis datos son los mismos", false, "N"],
 ["borren la cebolla de mis tacos, mis datos ya los tienen", false, "N"],
 ["quita el queso, mis datos ya los tienes", false, "N"],
 ["necesitan mis datos para apartar?", false, "N"],
 ["olvide dar mis datos, soy Ana, calle 10", false, "N"],
 ["saquen la cuenta, mis datos son los de siempre", false, "N"],
 ["olviden el refresco, mis datos son los mismos", false, "N"],
 ["den de baja el pedido, mis datos ya los tienen", false, "N"],
 ["eliminen el pedido de ayer, mis datos ya los tienen", false, "N"],
 ["mi info de envio: calle 20 x 15, 2 tortas", false, "N"],
 ["no me llega la confirmacion de su sistema", false, "N"],
 ["quiero ver el menu, mis datos son Juan 9991234567", false, "N"],
 ["corrijan la direccion de mi pedido, mis datos son calle 5", false, "N"],
 ["actualiza mi direccion de entrega a calle 8, mi numero es 999", false, "N"],
 ["quiten la tarjeta, pago en efectivo, mis datos ya los tienen", false, "N"],


 // --- corpus propio (recall-first): jerga, mayusculas, sin acentos, pronombres pegados, "en su sistema" ---
 ["QUIERO QUE BORREN MIS DATOS", true],
 ["q borren mis datos xfa", true],
 ["kiero k me borren de su sistema", true],
 ["borrenme de su lista", true],
 ["bórrenme de su base de datos por favor", true],
 ["eliminenme de sus registros", true],
 ["quiero que me eliminen de su sistema ya", true],
 ["olvidenme", true],
 ["olviden mi numero", true],
 ["ya no quiero que tengan mi numero", true],
 ["no quiero que guarden mi direccion", true],
 ["no quiero q guarden mi info", true],
 ["no quiero que me sigan mandando mensajes, borren mi numero", true],
 ["dejen de enviarme mensajes por favor", true],
 ["dejen de molestarme con promociones, quiten mis datos", true],
 ["quiero darme de baja de sus promociones y de sus datos", true],
 ["denme de baja", true],
 ["den de baja mi cuenta", true],
 ["cancelen mi cuenta", true],
 ["cancela mi cuenta y borra mis datos", true],
 ["quiero cancelar mis datos personales", true],
 ["solicito la cancelacion de mis datos", true],
 ["solicito la supresion de mis datos personales", true],
 ["ejerzo mi derecho de oposicion", true],
 ["me opongo al tratamiento de mis datos", true],
 ["me opongo a que me contacten", true],
 ["no autorizo que usen mi informacion", true],
 ["no consiento el uso de mis datos para publicidad", true],
 ["retiro mi consentimiento", true],
 ["revoco la autorizacion que di", true],
 ["quiero saber que informacion tienen de mi", true],
 ["que tienen guardado de mi?", true],
 ["que datos mios guardan", true],
 ["quiero acceder a mi informacion personal", true],
 ["necesito una copia de mis datos", true],
 ["quiero ver que datos tienen de mi persona", true],
 ["mandenme los datos que tienen mios", true],
 ["quiero rectificar mi nombre en sus datos", true],
 ["corrijan mis datos, mi correo esta mal", true],
 ["actualicen mis datos, cambie de telefono", true],
 ["mis datos estan equivocados", true],
 ["la informacion que tienen de mi es incorrecta", true],
 ["tienen aviso de privacidad?", true],
 ["donde veo su aviso de privacidad", true],
 ["quiero ejercer mis derechos ARCO", true],
 ["como ejerzo mis derechos arco?", true],
 ["que hacen con mi informacion personal", true],
 ["con quien comparten mis datos?", true],
 ["ya pedi un pedido y quiero que borren mis datos", true],
 ["ya les di mis datos de factura, ahora borrenlos", true],
 ["despues de que me entreguen mi pedido borren mis datos", true],
 ["si no hago otro pedido borren mi info", true],
 ["podrian borrar mis datos?", true],
 ["me gustaria que eliminaran mis datos", true],
 ["quisiera que no guardaran mis datos", true],
 ["no vuelvan a usar mis datos", true],
 ["ya no quiero estar en su base de datos", true],
 ["no quiero aparecer en su lista", true],
 ["saquen mi numero de su lista", true],
 ["quiten mi numero de su sistema", true],
 ["eliminen mi perfil", true],
 ["borren mi historial de pedidos y mis datos", true],
 ["borren todo lo que tengan de mi", true],
 ["quiero que me olviden", true],
 ["que me quiten de su base", true],
 ["borra mis datos", true],
 ["eliminar mis datos", true],
 ["quiero que eliminen mi informacion", true],
 ["pido que supriman mis datos", true],
 ["en cumplimiento de la ley, borren mis datos personales", true],
 ["PROFECO: exijo que eliminen mis datos", true],
 ["ya borre la app, ahora borren mis datos", true],
 ["necesito mi factura, pero despues borren mis datos", true],
 ["factura por favor y luego eliminen mis datos", true],
 // --- NO ARCO (pedidos y factura normales; los FP que queden se asumen y los suaviza el menu) ---
 ["hola quiero 3 tacos de pastor", false],
 ["quiero un pedido para recoger", false],
 ["cuanto cuesta el kilo de cochinita", false],
 ["a que hora cierran", false],
 ["gracias", false],
 ["si, confirmo", false],
 ["quiero mi factura", false],
 ["necesito factura de mi ultimo pedido", false],
 ["mi RFC es XAXX010101000", false],
 ["facturame a nombre de Juan Perez", false],
 ["ya llego mi pedido, gracias", false],
 ["donde esta mi pedido", false],
 ["cancelen mi pedido", false],
 ["quiero cancelar mi orden", false],
 ["cancela la orden de hace rato", false],
 ["cambia mi direccion de entrega", false],
 ["mi direccion es calle 60 x 45 centro", false],
 ["agregale una coca a mi orden", false],
 ["sin cebolla por favor", false],
 ["quitale el cilantro a los tacos", false],
 ["borra el ultimo taco que agregue", false],
 ["quita la salsa verde", false],
 ["cambia el pedido a 4 tacos", false],
 ["el pago sera con tarjeta", false],
 ["mi telefono es 9991234567", false],
 ["mi nombre es Juan", false],
 ["que tienen de postre", false],
 ["que tienen de bebidas", false],
 ["que hay de comer", false],
 ["que tienen de menu hoy", false],
 ["tienen servicio a domicilio", false],
 ["ya hice mi pedido", false],
 ["necesito corregir mi pedido, era sin picante", false],
 ["actualiza mi pedido con una orden de guacamole", false],
 ["me pueden mandar el ticket", false],
 ["envien el pedido a la oficina", false],
 ["entreguen en la puerta", false],
 ["ver el menu", false],
 ["saber el horario de la sucursal", false],
 ["quiero saber si tienen pozole", false],
];
