export { ANCLA_EVENTO, EVENTOS_AUTOMATICOS, MAX_MENSAJES_POR_CORRIDA, OFFSET_HORAS_MAX, OFFSET_HORAS_MIN, OFFSET_HORAS_SUGERIDO, VENTANA_GRACIA_HORAS, esEventoAutomatico } from "./tipos.ts";
export type { CandidatoMensajeAutomatico, EntradaProgramacion, EventoAutomatico, ProgramacionMensaje, ResultadoMensajesAutomaticos, ResumenMensajesAutomaticos } from "./tipos.ts";
export { enVentanaDisparo, instanteDisparo, instanteDisparoDeCandidato } from "./ventana.ts";
export { VARIABLES_PLANTILLA, construirVariables, variablesNoSoportadas } from "./variables.ts";
export type { VariablePlantillaInfo } from "./variables.ts";
export { ejecutarMensajesAutomaticos } from "./ejecutor.ts";
export type { BorradorAutomaticoCreado, ContextoMensajesAutomaticos, WithMensajesAutomaticosTx } from "./ejecutor.ts";
export type { RentasMensajesAutomaticosRepository } from "./repository.ts";
export { InMemoryRentasMensajesAutomaticosRepository } from "./in-memory-repository.ts";
export type { BorradorAutomaticoEnMemoria } from "./in-memory-repository.ts";
export { PostgresRentasMensajesAutomaticosRepository } from "./postgres-repository.ts";
