// Corpus del detector de crisis: frases que DEBEN disparar la guardia (por familia) y frases parecidas que NO deben dispararla. Las del
// QA adversarial de citas R1 (agentes-02, features-07/08, viaje-07/08) van incluidas.
import { CRISIS_SENALES } from "../../src/crisis-detector.ts";

export const POSITIVAS: Readonly<Record<string, readonly string[]>> = {
  [CRISIS_SENALES.ideacion]: [
    // Segunda ronda (revision independiente)
    "ya me quiero ir de este mundo",
    "no quiero estar aquí",
    "quiero que todo se acabe",
    "quiero que todo termine",
    "me qiero morir",
    "me quiero mori",
    "quiero morime",
    "qiero morirme",
    // Directas (QA R1)
    "me quiero morir",
    "Me quiero morir, ya no sé qué hacer",
    "me voy a suicidar",
    "Creo que me voy a suicidar",
    "me quiero suicidar",
    "me voy a matar",
    "Me voy a matar",
    "quiero quitarme la vida",
    "Estoy pensando en quitarme la vida",
    "kiero morirme",
    "ya no quiero estar aqui",
    "ya no quiero seguir viviendo",
    "quiero  morirme",
    "quiero\nmorirme",
    "quiero morirme",
    "no quiero vivir",
    "La verdad ya no quiero vivir",
    "Ya no quiero vivir, mejor cancela todo",
    "me quiero matar",
    "quiero matarme",
    "pensando en morir",
    "estoy pensando en suicidarme",
    "suicidio",
    "quiero acabar con mi vida",
    "sigo pensando en acabar con mi vida",
    "voy a acabar con mi vida esta semana",
    "quiero terminar con todo",
    "ya quiero terminar con todo esto",
    "voy a terminar con todo",
    "quisiera morir",
    "quisiera morirme y ya",
    "ojalá me muriera",
    "ojala no despertara mañana",
    "ojala no existiera",
    "quiero desaparecer",
    "quisiera desaparecer para siempre",
    "me gustaría no existir",
    "prefiero estar muerto",
    "prefiero estar muerta",
    "estaría mejor muerto",
    "mejor muerta",
    "quiero dormir y no despertar",
    "ya no quiero despertar",
    "no quiero seguir viviendo",
    "no quiero seguir vivo",
    "no quiero existir",
    "no puedo seguir viviendo así",
    "no vale la pena vivir",
    "la vida no vale la pena",
    "mi vida no vale nada",
    "no tengo razón para vivir",
    "no tengo ningún motivo para seguir viviendo",
    "no encuentro razones para vivir",
    "para qué seguir viviendo",
    "para que vivir",
    "estoy harto de la vida",
    "harta de vivir",
    "cansada de la vida",
    "odio mi vida",
    "odio vivir",
    "estarían mejor sin mí",
    "ESTARÍAN MEJOR SIN MÍ",
    "mi familia estaría mejor sin mi",
    "seria mejor si no estuviera",
    "mejor si me muriera",
    "nadie me va a extrañar",
    "a nadie le importo",
    "a nadie le importaría si me muero",
    "quiero dejar de vivir",
    "quiero dejar de existir",
    "quiero irme de este mundo",
    "mi hijo se quiere suicidar",
    "mi esposo dice que se quiere matar",
    "mi hermana intentó suicidarse",
    "mi hija se quiere quitar la vida",
    "se quiere morir",
    "intenté suicidarme anoche",
    "ya intenté matarme una vez",
    "pienso en morirme todos los días",
    "tengo ideas de morir",
    "tengo pensamientos de muerte",
    "me quiero morir ya",
    "me quiero ya morir",
    "ya me quiero morir",
    "ME QUIERO MORIR",
    "Me Quiero Morir!!!",
    "quieroooo morirme",
    "kiero morir",
    "kero morirme",
    "quiero morrirme",
    "me voy a suisidar",
    "me quiero sucidar",
    "me quiero suisidar",
    "quiero suicidarme 😭",
    "💔 me quiero morir 💔",
    "me quiero morir...",
    "me.quiero.morir",
    "m3 quier0 morirm3",
    "me quiero m0rir",
    "m4tarme",
    "quiero m4tarme",
    "su1c1darme",
    "m a t a r m e",
    "s u i c i d a r m e",
    "la neta me quiero morir",
    "ya valió todo, me quiero morir",
    "ya no quiero seguir viviendo, nomás quería avisarles",
    "ya no quiero estar en este mundo",
    "ya no quiero existir",
    "no quiero volver a despertar",
    "ojalá no amaneciera",
    "ojalá me atropellara un carro y me muriera",
    "i want to die",
    "I want to kill myself",
    "i wanna die",
    "i dont want to live anymore",
    "I don't want to be here anymore",
    "I'm going to end my life",
    "everyone would be better off without me",
    "I have no reason to live",
    "suicidal",
    "suicide",
  ],
  [CRISIS_SENALES.plan]: [
    // Segunda ronda (revision independiente)
    "me voy a dar un tiro",
    "darme un tiro",
    "me quiero dar un balazo",
    "me quiero aventar",
    "me voy a aventar",
    "me voy a colgar de una viga",
    "me voy a ahorcar",
    "quiero ahorcarme",
    "me voy a colgar",
    "voy a envenenarme",
    "me voy a pegar un tiro",
    "voy a pegarme un balazo",
    "me voy a volar la cabeza",
    "quiero cortarme las venas",
    "me voy a cortar las venas",
    "me voy a abrir las venas",
    "me voy a cortar las muñecas",
    "me voy a aventar del puente",
    "me voy a tirar del edificio",
    "voy a saltar del balcón",
    "me quiero aventar a las vías del metro",
    "me quiero tirar de la azotea",
    "me voy a lanzar de un puente",
    "me voy a tomar todas las pastillas",
    "me tomé toda la caja de pastillas",
    "quiero tomarme todo el frasco de pastillas",
    "me voy a provocar una sobredosis",
    "quiero una sobredosis",
    "tengo una pistola para matarme",
    "tengo pastillas para dormirme para siempre",
    "ya tengo un plan para morir",
    "tengo un plan para acabar con todo",
    "compré una soga para hacerlo",
    "ya compré veneno y es para acabar con mi vida",
    "esta noche lo hago",
    "esta noche me mato",
    "esta noche acabo con todo",
    "ya decidí cómo matarme",
    "ya decidi como acabar con mi vida",
    "me voy a disparar",
    "me voy a electrocutar",
  ],
  [CRISIS_SENALES.autolesion]: [
    "me corto",
    "me corto los brazos",
    "me corto las muñecas cuando me siento mal",
    "me estoy cortando",
    "me estoy cortando los brazos otra vez",
    "me he cortado los muslos",
    "volví a cortarme los brazos",
    "me hago daño",
    "me hago daño a propósito",
    "me lastimo",
    "me lastimo a mi misma",
    "me lastimo para sentir algo",
    "me hago daño para calmarme",
    "quiero hacerme daño",
    "quiero hacerme daño a mi mismo",
    "quiero lastimarme",
    "quiero cortarme",
    "quiero cortarme los brazos",
    "me quiero lastimar",
    "me quiero cortar",
    "voy a hacerme daño",
    "tengo ganas de hacerme daño",
    "me dan ganas de lastimarme",
    "me castigo",
    "necesito castigarme",
    "me hiero",
    "me golpeo a propósito",
    "me hago cortes en los brazos",
    "me autolesiono",
    "autolesión",
    "me autolesioné de nuevo",
    "mi hija se autolesiona",
    "mi hijo se corta los brazos",
    "me quemo la piel a propósito",
    "me hago sangrar",
    "me lastimo seguido",
    "me corto a diario",
    "me corto y no puedo parar",
    "I want to hurt myself",
    "I self harm",
    "I cut myself on purpose",
    "I keep hurting myself",
  ],
  [CRISIS_SENALES.despedida]: [
    "adiós a todos",
    "adios a todos, los quiero",
    "me despido de todos",
    "me despido de ustedes",
    "despídanse de mí",
    "ya me despedí de mi familia",
    "no me busquen",
    "este es mi último mensaje",
    "Este es mi ultimo mensaje",
    "es mi última despedida",
    "les escribo mi carta de despedida",
    "dejé una carta suicida",
    "perdóname por lo que voy a hacer",
    "perdonenme por lo que voy a hacer",
    "cuiden a mis hijos cuando ya no esté",
    "cuida de mi perro cuando yo no esté",
    "ya no les voy a dar más molestias",
    "ya no voy a causar más problemas",
    "soy una carga para todos",
    "soy un estorbo",
    "soy una carga",
  ],
  [CRISIS_SENALES.desesperanza]: [
    // Segunda ronda (revision independiente)
    "no aguanto más la vida",
    "ya no aguanto la vida",
    "no le veo sentido",
    "ya no le veo sentido a nada",
    "no le veo sentido a la vida",
    "no le encuentro sentido a vivir",
    "no le veo sentido a seguir",
    "no tiene sentido seguir",
    "ya no tiene sentido vivir",
    "no tiene ningún sentido mi vida",
    "no veo salida",
    "no veo ninguna salida",
    "ya no hay esperanza para mí",
    "no hay salida a esto",
    "ya no veo esperanza",
    "no aguanto más",
    "no aguanto mas",
    "ya no aguanto",
    "Ya no aguanto.",
    "ya no aguanto, necesito ayuda",
    "ya no puedo más",
    "ya no puedo mas, quiero cita",
    "ya no puedo más con todo",
    "ya no puedo más con esto",
    "ya no puedo más con mi vida",
    "ya no puedo mas de todo",
    "ya no soporto más",
    "no soporto más esta vida",
    "ya no resisto más",
    "no aguanto más con esto",
    "ya no puedo con esto",
    "ya no puedo con mi vida",
    "ya no puedo seguir",
    "ya no puedo seguir así",
    "ya no puedo seguir con esto",
    "ya no puedo seguir adelante",
    "ya no puedo seguir fingiendo",
    "me rindo",
    "me rindo con todo",
    "ya me rendí",
    "me rindo con la vida",
    "ya no quiero seguir así",
    "ya no quiero seguir aquí",
    "no aguantooooo más",
    "ya no aguantoooo",
    "ya no puedo más 😭",
    "ya no\npuedo mas",
    "ya  no  puedo  mas",
    "ya no puedo mas y necesito ayuda",
    "ya no puedo mas por favor",
    "ya no puedo mas ayuda",
  ],
};

export const NEGATIVAS: readonly string[] = [
  // Agenda normal
  "Quiero agendar una cita para el jueves",
  "Quiero agendar una cita para mañana a las 10",
  "¿Tienen disponibilidad el lunes por la tarde?",
  "Necesito cancelar mi cita de mañana",
  "Quiero reagendar mi cita para el viernes",
  "¿Cuánto cuesta una limpieza dental?",
  "Hola, buenas tardes",
  "¿Cuál es su dirección?",
  "¿Aceptan tarjeta?",
  "Gracias, hasta luego",
  "Mi cita es a las 5:30, ¿puedo llegar 10 minutos tarde?",
  "¿Me pueden mandar la factura?",
  "Quiero una cita con el doctor Pérez",
  "¿Atienden los sábados?",
  "Necesito una cita urgente para hoy",
  // Falsos positivos de QA R1
  "se me cortó la llamada",
  "Se me cortó la llamada, ¿me pueden marcar?",
  "la ortodoncia me lastimó la encía",
  "el lunes ya no puedo más tarde de las 5",
  "Ya no puedo más tarde de las 5",
  "me corto el pelo el sábado, ¿puedo ir el domingo?",
  "quiero terminar con todo el tratamiento",
  "Quiero terminar con todo el tratamiento de ortodoncia este año",
  "Me lastimo la rodilla cada vez que corro, quiero una cita",
  "Me corto con el hilo dental cada vez que lo uso, ¿es normal?",
  "me hago daño en la muela al morder, quiero una cita",
  "Ya no aguanto el dolor de muela, necesito cita hoy mismo",
  "¿Me corto las uñas antes de la cirugía o no hace falta?",
  "Ya no puedo más con este dolor de la endodoncia, ¿hay lugar mañana?",
  // Dolor y molestias físicas
  "ya no aguanto el dolor de espalda",
  "ya no aguanto la sensibilidad en los dientes",
  "No aguanto el dolor, ¿pueden atenderme hoy?",
  "ya no soporto el olor del consultorio de al lado",
  "no aguanto el calor que hace en la sala de espera",
  "ya no aguanto la comezón en el ojo",
  "ya no puedo mover el brazo por el dolor",
  "ya no puedo masticar del lado izquierdo",
  "ya no puedo dormir por el dolor de muela",
  "ya no puedo caminar bien desde la operación",
  "ya no puedo respirar bien por la nariz",
  "ya no puedo abrir la boca",
  "ya no puedo más tarde, salgo a las 6",
  "ya no puedo mas temprano de las 9",
  "me lastimo la espalda cuando cargo a mi hijo",
  "me lastimé el tobillo jugando fútbol",
  "me lastimó el brazo el dentista de antes",
  "me cortó la encía el otro dentista",
  "me corté el dedo con un cuchillo de cocina, ¿pueden verlo?",
  "me corto las uñas yo solo, ¿qué hago con la uña enterrada?",
  "me corto el cabello cada mes",
  "me cortaron la luz y no vi su mensaje",
  "me hago daño al apretar los dientes, ¿qué recomiendan?",
  "me hago daño en el hombro al levantar pesas",
  "me lastimo el cuello al dormir",
  "mi perro se lastimó la pata",
  "mi gato se cortó con un vidrio",
  "mi perro se hace daño al morder la jaula",
  // Terminar / acabar con objeto concreto
  "terminar con todo el papeleo",
  "quiero terminar con todo esto de los trámites del seguro",
  "terminar con todos los pendientes de mi expediente",
  "acabar con el dolor de muela",
  "quiero acabar con la caries de una vez",
  "quiero acabar con el sarro",
  "ya quiero terminar con las revisiones",
  "terminar con el tratamiento de conducto",
  "acabar con todos los pendientes antes de mi cita",
  // Morir / matar figurado o de otra persona sin deseo propio
  "me muero de hambre, ¿hay lugar para comer antes?",
  "me muero de risa con su recepcionista",
  "me muero de ganas de que me quiten la ortodoncia",
  "me muero de miedo con el dentista",
  "me quiero morir de la vergüenza, llegué tarde a mi cita",
  "mi perro se va a morir si no lo atienden hoy",
  "no quiero que mi perro se muera, ¿pueden verlo?",
  "mi gata se está muriendo, necesito atención urgente",
  "el paciente anterior casi se desmaya del dolor",
  "mi abuelito falleció la semana pasada, cancelo su cita",
  "quiero cancelar la cita de mi mamá porque falleció",
  "me quiero matar de risa con ese chiste",
  "me mato trabajando y no tengo tiempo, ¿hay citas en la noche?",
  "estoy matando el tiempo en la sala de espera",
  // Seguir / dejar / no querer sin crisis
  "ya no quiero seguir con el tratamiento de ortodoncia",
  "ya no quiero seguir con el mismo doctor, ¿puedo cambiar?",
  "no quiero seguir esperando, ¿cuánto falta?",
  "no puedo seguir con la dieta que me dieron",
  "ya no puedo seguir tomando ese medicamento, me cae mal",
  "no quiero vivir con dolor, quiero una solución para mi muela",
  "no puedo seguir al doctor por teléfono, se corta la señal",
  "dejar de fumar, ¿me pueden ayudar?",
  "quiero dejar de tomar el medicamento, ¿puedo?",
  "no tiene sentido pagar dos veces la consulta",
  "no le veo sentido a repetir la radiografía",
  "no le veo sentido a ese cobro extra",
  "no veo la salida del estacionamiento",
  "no hay salida de emergencia en el segundo piso, ¿es seguro?",
  "no le encuentro sentido a este formulario",
  "me rindo, no encuentro estacionamiento",
  "me rindo, no logro abrir el enlace de la cita",
  // Falsos positivos de salud (segunda ronda, revision independiente)
  "¿me tomo todas las pastillas del antibiótico?",
  "me tomé todas las pastillas que me recetaron, ¿ahora qué sigo?",
  "la endodoncia me mató",
  "el dolor me mató",
  "quiero desaparecer el sarro",
  "quiero desaparecer las manchas de los dientes",
  "no quiero despertar temprano",
  "no quiero despertar tarde mañana",
  "ultimo mensaje: confirmo la cita",
  "no me busquen el lunes, estaré de viaje",
  "me quiero colgar el gafete",
  "me voy a colgar el cuadro del consultorio",
  // Inglés benigno
  "I want to book an appointment for Monday",
  "i want to die laughing, that joke was so good",
  "I cut myself shaving yesterday, can I get it checked?",
];
