// Catalogo de eventos de notificacion in-app (core.notification) por vertical y superadmin.
//
// UNA sola tabla de datos: cada evento importante del ciclo (algo nuevo que atender, algo que fallo,
// algo por vencer, una aprobacion pendiente, un costo/umbral, un cierre) con su id estable, categoria,
// severidad, roles destinatarios, icono, texto SIN PII (plantilla con parametros numericos o codigos
// cortos, nunca nombres ni texto libre), enlace a la pantalla origen y regla de dedupe/expiracion.
//
// `productor.estado`:
//   * "conectado": existe un productor real que llama `emitirNotificacion(<id>)`; `archivo` apunta a
//     el. La prueba `tests/notificaciones-catalogo.spec.ts` verifica que el archivo existe y contiene el
//     id, que el enlace corresponde a una ruta real de apps/web y que el texto no admite PII.
//   * "pendiente": la feature origen existe (o esta en otro PR) pero su productor aun no se conecta;
//     `motivo` dice exactamente que falta. Es un hueco declarado, nunca un evento fingido.
//
// Enlace: `{orgSlug}` lo resuelve la base y `{entidadId}` (opcional, solo si el evento apunta al detalle de una entidad) lo sustituye
// `emitirNotificacion` con el `entidadId` de la emision.
//
// Destinatarios: SIEMPRE owner/admin de la organizacion (platform_role) mas los `roles` de vertical
// listados; los eventos de ambito "superadmin" van a core.platform_superadmin. El enlace usa el
// marcador {orgSlug}, que la base sustituye por el slug real (core.emit_notification).

export const AMBITOS_NOTIFICACION = ["restaurantes", "hoteles", "citas", "licitaciones", "rentas", "despachos", "superadmin"] as const;
export type AmbitoNotificacion = (typeof AMBITOS_NOTIFICACION)[number];

export const CATEGORIAS_NOTIFICACION = [
  "onboarding",
  "operacion",
  "agentes",
  "aprobaciones",
  "automatizaciones",
  "cobranza",
  "fiscal",
  "seguridad",
  "salud",
  "cierres",
] as const;
export type CategoriaNotificacion = (typeof CATEGORIAS_NOTIFICACION)[number];

export type SeveridadNotificacion = "info" | "atencion" | "critica";

export type ProductorNotificacion =
  | { readonly estado: "conectado"; readonly archivo: string; readonly nota?: string }
  | { readonly estado: "pendiente"; readonly motivo: string };

export interface EventoNotificacion {
  readonly id: string;
  readonly ambito: AmbitoNotificacion;
  readonly categoria: CategoriaNotificacion;
  readonly severidad: SeveridadNotificacion;
  /** Roles de vertical (ademas de owner/admin de plataforma). Vacio = solo owner/admin. */
  readonly roles: readonly string[];
  /** Nombre del icono de lucide-react que usara la pantalla de notificaciones. */
  readonly icono: string;
  /** Plantillas: solo `{param}` declarados en `parametros`. Sin PII por construccion. */
  readonly titulo: string;
  readonly cuerpo: string | null;
  readonly parametros: readonly string[];
  /** Ruta interna de apps/web; `{orgSlug}` lo resuelve la base. */
  readonly enlace: string;
  /** Regla de dedupe legible; la clave real es `<id>:<clave del productor>`. */
  readonly dedupe: string;
  /** Dias de vigencia antes de expirar. */
  readonly venceDias: number;
  readonly productor: ProductorNotificacion;
}

// ---- Plan, tope de mensajes y fin de prueba (PL-16) ------------------------------------------------
// Mismos tres avisos en las 6 verticales (owner/admin) y dos de plataforma (superadmin). Texto sin PII: solo numeros y el slug de la
// organizacion como codigo. La pantalla de destino (`Plan y uso`) la monta apps/web en cada vertical.
const VERTICALES_PLAN = ["restaurantes", "hoteles", "rentas", "licitaciones", "citas", "despachos"] as const;

function eventosPlan(v: (typeof VERTICALES_PLAN)[number]): EventoNotificacion[] {
  const medidor = { estado: "conectado", archivo: "apps/api/src/plan-topes/medidor.ts" } as const;
  const prueba = { estado: "conectado", archivo: "apps/api/src/plan-topes/aviso-prueba.ts", nota: "sale en el cron diario /internal/plataforma/prueba-avisos (vercel.json, 14:00 UTC)" } as const;
  return [
    { id: `${v}.plan.mensajes_80`, ambito: v, categoria: "cobranza", severidad: "atencion", roles: [], icono: "Gauge", titulo: "Va en el 80 por ciento del tope de mensajes de su plan", cuerpo: "Mensajes del mes: {usado} de {limite}.", parametros: ["usado", "limite"], enlace: `/${v}/{orgSlug}/plan`, dedupe: "una por organizacion por mes", venceDias: 10, productor: { ...medidor, nota: "solo mide el WhatsApp saliente de citas, hoteles y restaurantes" } },
    { id: `${v}.plan.mensajes_excedido`, ambito: v, categoria: "cobranza", severidad: "critica", roles: [], icono: "Gauge", titulo: "Se alcanzó el tope de mensajes de su plan", cuerpo: "Mensajes del mes: {usado} de {limite}. Revise su plan.", parametros: ["usado", "limite"], enlace: `/${v}/{orgSlug}/plan`, dedupe: "una por organizacion por mes", venceDias: 10, productor: { ...medidor, nota: "solo mide el WhatsApp saliente de citas, hoteles y restaurantes" } },
    { id: `${v}.plan.prueba_por_vencer`, ambito: v, categoria: "cobranza", severidad: "atencion", roles: [], icono: "Clock", titulo: "Su prueba está por terminar", cuerpo: "Días restantes: {dias}. Revise Plan y uso para ver el estado de su cuenta.", parametros: ["dias"], enlace: `/${v}/{orgSlug}/plan`, dedupe: "una por organizacion por umbral (7, 3 y 1 dia) y fecha de fin", venceDias: 8, productor: prueba },
  ];
}

const EVENTOS_PLAN: readonly EventoNotificacion[] = [
  ...VERTICALES_PLAN.flatMap(eventosPlan),
  { id: "superadmin.plan.mensajes_80", ambito: "superadmin", categoria: "cobranza", severidad: "atencion", roles: [], icono: "Gauge", titulo: "Una organización va en el 80 por ciento de su tope de mensajes", cuerpo: "Organización: {organizacion}. Mensajes del mes: {usado} de {limite}.", parametros: ["organizacion", "usado", "limite"], enlace: "/superadmin/planes", dedupe: "una por organizacion por mes", venceDias: 10, productor: { estado: "conectado", archivo: "apps/api/src/plan-topes/medidor.ts", nota: "solo mide el WhatsApp saliente de citas, hoteles y restaurantes" } },
  { id: "superadmin.plan.mensajes_excedido", ambito: "superadmin", categoria: "cobranza", severidad: "atencion", roles: [], icono: "Gauge", titulo: "Una organización alcanzó el tope de mensajes de su plan", cuerpo: "Organización: {organizacion}. Mensajes del mes: {usado} de {limite}.", parametros: ["organizacion", "usado", "limite"], enlace: "/superadmin/planes", dedupe: "una por organizacion por mes", venceDias: 10, productor: { estado: "conectado", archivo: "apps/api/src/plan-topes/medidor.ts", nota: "solo mide el WhatsApp saliente de citas, hoteles y restaurantes" } },
];

export const CATALOGO_NOTIFICACIONES: readonly EventoNotificacion[] = [
  // ---- Restaurantes -------------------------------------------------------------------------------
  { id: "restaurantes.pedido.nuevo", ambito: "restaurantes", categoria: "operacion", severidad: "info", roles: ["staff"], icono: "ShoppingBag", titulo: "Pedido nuevo por atender", cuerpo: null, parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "un aviso por pedido (clave = id del pedido)", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/postgres-repository.ts" } },
  { id: "restaurantes.pedido.programado_en_cocina", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "CalendarRange", titulo: "Un pedido programado entró a cocina", cuerpo: "Ya toca prepararlo; revisa el detalle en Pedidos.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "un aviso por pedido (clave = id del pedido)", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/pedidos-programados-avisos.ts", nota: "sale al promover el pedido a pending: cron promover-programados, el panel de pedidos al consultar o el adelanto manual" } },
  { id: "restaurantes.pedido.programado_atrasado", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "TriangleAlert", titulo: "Un pedido programado entró a cocina con retraso: confirme con el cliente", cuerpo: "Pasó más de una hora de la hora pedida (por ejemplo, el cron estuvo pausado). Confirme con el cliente antes de cocinarlo.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "un aviso por pedido atrasado (clave = id del pedido); sustituye al aviso normal de entrada a cocina", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/pedidos-programados-avisos.ts", nota: "sale en lugar del aviso normal si el pedido entra a cocina con mas de 1 h de retraso (cron promover-programados, promocion al consultar el panel o adelanto manual)" } },
  { id: "restaurantes.whatsapp.mensaje_muerto", ambito: "restaurantes", categoria: "salud", severidad: "atencion", roles: ["staff"], icono: "MessageSquareWarning", titulo: "Un WhatsApp al cliente no se pudo entregar", cuerpo: "Un mensaje (por ejemplo, el estado de un pedido) agotó sus reintentos o fue rechazado. Avise al cliente por otro medio.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "un aviso por mensaje muerto (clave = id del mensaje del outbox)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/internal/whatsapp-dispatch.ts" } },
  { id: "restaurantes.whatsapp.entrega_fallida_pedido", ambito: "restaurantes", categoria: "salud", severidad: "atencion", roles: ["staff"], icono: "MessageSquareWarning", titulo: "Un aviso de su pedido no llegó al cliente por WhatsApp", cuerpo: "Meta no entregó el mensaje (motivo: {motivo}). Si el cliente dejó correo, se le envió por correo; si no, avísele por otro medio.", parametros: ["motivo"], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "un aviso por mensaje fallido (clave = id del mensaje del outbox)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/whatsapp.ts", nota: "sale cuando Meta reporta `failed` por el webhook (statuses); el aviso de estado de un pedido tambien se respalda por correo si el cliente dejo uno" } },
  { id: "restaurantes.whatsapp.entrega_fallida", ambito: "restaurantes", categoria: "salud", severidad: "atencion", roles: ["staff"], icono: "MessageSquareWarning", titulo: "Un WhatsApp al cliente no se entregó", cuerpo: "Meta no entregó un mensaje de la conversación (motivo: {motivo}). Revise la conversación y avise al cliente por otro medio.", parametros: ["motivo"], enlace: "/restaurantes/{orgSlug}/conversaciones", dedupe: "un aviso por mensaje fallido (clave = id del mensaje del outbox)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/whatsapp.ts", nota: "mismo productor que el aviso de pedido, para los mensajes que no son un aviso de estado de pedido" } },
  { id: "restaurantes.whatsapp.entregas_fallidas_varias", ambito: "restaurantes", categoria: "salud", severidad: "critica", roles: ["staff"], icono: "MessageSquareWarning", titulo: "Varios WhatsApp al cliente no se entregaron en la última hora", cuerpo: "Van {cantidad} entregas fallidas en la última hora. Revise el indicador de entrega en Agente de WhatsApp.", parametros: ["cantidad"], enlace: "/restaurantes/{orgSlug}/agente-whatsapp", dedupe: "un aviso por organizacion por hora (clave = organizacion + hora UTC); sustituye a los avisos individuales cuando hay mas de 5 fallos en una hora", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/whatsapp.ts", nota: "agrupa los fallos de entrega para no inundar la campana" } },
  { id: "restaurantes.handoff.solicitado", ambito: "restaurantes", categoria: "agentes", severidad: "atencion", roles: ["staff"], icono: "UserRoundCog", titulo: "Un cliente pide hablar con una persona", cuerpo: "El agente derivó una conversación a atención humana.", parametros: [], enlace: "/restaurantes/{orgSlug}/conversaciones", dedupe: "una por conversacion derivada", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/conversaciones/postgres-repository.ts" } },
  { id: "restaurantes.voz.llamada_escalada", ambito: "restaurantes", categoria: "agentes", severidad: "atencion", roles: ["staff"], icono: "PhoneCall", titulo: "Una llamada pasó a una persona", cuerpo: "El agente de voz no pudo cerrar la llamada y dejó un aviso para devolverla.", parametros: [], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por llamada", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/voz-interno.ts" } },
  { id: "restaurantes.voz.proveedor_con_fallas", ambito: "restaurantes", categoria: "salud", severidad: "atencion", roles: [], icono: "TriangleAlert", titulo: "El proveedor de voz está registrando errores", cuerpo: "Revise el estado del servicio de voz en Indicadores.", parametros: [], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por sucursal por hora", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/voz-interno.ts" } },
  { id: "restaurantes.callback.pendiente", ambito: "restaurantes", categoria: "agentes", severidad: "atencion", roles: ["staff"], icono: "PhoneCall", titulo: "Un cliente dejó un contacto para devolverle la llamada", cuerpo: "El agente anotó una solicitud de contacto pendiente.", parametros: [], enlace: "/restaurantes/{orgSlug}/conversaciones", dedupe: "una por solicitud de contacto (clave = id)", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/postgres-repository.ts" } },
  { id: "restaurantes.cliente.llego", ambito: "restaurantes", categoria: "operacion", severidad: "critica", roles: ["staff"], icono: "MapPin", titulo: "Un cliente llegó a recoger su pedido", cuerpo: "El cliente avisó por WhatsApp que ya está en la sucursal. Revise el pedido para recoger en la bandeja de pedidos.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por aviso de llegada (clave = id de la solicitud de contacto)", venceDias: 1, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/postgres-repository.ts", nota: "sale con registrar_contacto(reason: cliente_llego) del agente de WhatsApp" } },
  { id: "restaurantes.voz.tope_mensual_80", ambito: "restaurantes", categoria: "cobranza", severidad: "atencion", roles: [], icono: "Gauge", titulo: "El gasto de voz del mes va en el 80 por ciento del tope", cuerpo: "Gasto del mes: {usado} de {limite} USD. Al llegar al tope, las llamadas nuevas se pasan a una persona.", parametros: ["usado", "limite"], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por organizacion por mes (clave = organizacion + periodo)", venceDias: 10, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/voz-llamada.ts", nota: "lo avisa el worker de telefonia al abrir una llamada; el tope vive en su configuracion (VOICE_TOPE_MENSUAL_USD / tabla DNIS)" } },
  { id: "restaurantes.voz.tope_mensual_alcanzado", ambito: "restaurantes", categoria: "cobranza", severidad: "critica", roles: [], icono: "Gauge", titulo: "Se alcanzó el tope de gasto de voz del mes", cuerpo: "Gasto del mes: {usado} de {limite} USD. Las llamadas nuevas se pasan a una persona (con callback) hasta el mes siguiente o hasta subir el tope.", parametros: ["usado", "limite"], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por organizacion por mes (clave = organizacion + periodo)", venceDias: 10, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/voz-llamada.ts", nota: "lo avisa el worker de telefonia cuando rechaza una llamada por el tope" } },
  { id: "restaurantes.voz.worker_sin_latido", ambito: "restaurantes", categoria: "salud", severidad: "critica", roles: [], icono: "TriangleAlert", titulo: "El worker de llamadas no reporta presencia", cuerpo: "Las llamadas no se estan atendiendo por voz: revise el estado del worker.", parametros: [], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por organizacion por hora", venceDias: 2, productor: { estado: "pendiente", motivo: "requiere el latido del worker (AP2 §2): el worker todavia no reporta presencia a la API ni hay un cron que lo vigile; hoy solo responde /salud 503 en su propio host" } },
  { id: "restaurantes.evento.solicitud", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "PartyPopper", titulo: "Llegó una solicitud de evento o catering", cuerpo: "Un cliente pidió cotización de un evento desde el sitio público.", parametros: [], enlace: "/restaurantes/{orgSlug}/conversaciones", dedupe: "una por solicitud de evento (clave = id de la solicitud)", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/postgres-repository.ts" } },
  { id: "restaurantes.pedido.entrega_tardia", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "Clock", titulo: "Un pedido va con retraso", cuerpo: "El pedido #{numero} pasó de su hora prometida y sigue sin entregarse.", parametros: ["numero"], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por pedido (clave = id del pedido)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/avisos-operativos.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min); la hora prometida es estimated_delivery_at, la hora de recogida o la creacion/hora programada mas el umbral de la sucursal (45 min por defecto)" } },
  { id: "restaurantes.pedido.programado_por_vencer", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "CalendarClock", titulo: "Un pedido programado necesita atención", cuerpo: "El pedido programado #{numero} está por llegar a su hora y no está listo (sin promover o sin repartidor asignado).", parametros: ["numero"], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por pedido (clave = id del pedido)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/avisos-operativos.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min)" } },
  { id: "restaurantes.pedido.incidencia_repartidor", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "Truck", titulo: "Un repartidor reportó un problema con un pedido", cuerpo: "Revise el pedido marcado con problema en la bandeja de pedidos.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por incidencia (clave = id del pedido + minuto UTC del reporte)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/repartidor-orders.ts" } },
  { id: "restaurantes.comanda.captura_manual_vencida", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "ClipboardList", titulo: "Una comanda espera captura manual en el POS", cuerpo: "Lleva {minutos} minutos sin capturarse en SoftRestaurant. Captúrela y márquela como capturada.", parametros: ["minutos"], enlace: "/restaurantes/{orgSlug}/comandas-pos", dedupe: "una por comanda (clave = id de la comanda)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/softrestaurant/alerta-vencida.ts", nota: "sale en el tick /internal/restaurantes/softrestaurant-dispatch (cada 5 min), antes de revisar si hay adaptador real; el umbral por sucursal (5 min por omision) se fija en Comandas al POS" } },
  { id: "restaurantes.proveedor.falla", ambito: "restaurantes", categoria: "salud", severidad: "critica", roles: [], icono: "TriangleAlert", titulo: "Falla un proveedor del agente", cuerpo: "Proveedor: {proveedor}.", parametros: ["proveedor"], enlace: "/restaurantes/{orgSlug}/configuracion", dedupe: "una por proveedor por dia", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/alertas-duenio/proveedor.ts", nota: "sale en el despachador /internal/whatsapp/dispatch (cada 5 min) cuando una organizacion acumula 3 o mas fallas de Meta o de la red en la corrida y ningun envio exitoso; la ventana es la corrida, no hay estado entre ticks" } },
  { id: "restaurantes.whatsapp.token_invalido", ambito: "restaurantes", categoria: "salud", severidad: "critica", roles: [], icono: "KeyRound", titulo: "El acceso de WhatsApp (token de Meta) es inválido o venció", cuerpo: "Meta rechazó el envío con error 190: el agente no puede contestar por WhatsApp hasta renovar el token.", parametros: [], enlace: "/restaurantes/{orgSlug}/configuracion", dedupe: "una por organizacion por dia (clave = proveedor y fecha de Merida)", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/alertas-duenio/proveedor.ts", nota: "sale de inmediato en el despachador /internal/whatsapp/dispatch al recibir el error 190 de Graph API; los avisos a 14, 7 y 1 dia de la expiracion requieren que la expiracion sea conocida (no se guarda hoy)" } },
  { id: "restaurantes.marketing.borrador_listo", ambito: "restaurantes", categoria: "aprobaciones", severidad: "atencion", roles: [], icono: "Megaphone", titulo: "Hay una campaña de reactivación lista para aprobar", cuerpo: "{conteo} clientes con consentimiento llevan {dias} días o más sin pedir. Revise el costo estimado y apruebe o rechace; nada se envía hasta que apruebe.", parametros: ["conteo", "dias"], enlace: "/restaurantes/{orgSlug}/campanas", dedupe: "una por campana (clave = id de la campana)", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/marketing/campanas.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min; la base crea a lo sumo un borrador por organizacion, segmento y dia); apagado por omision: requiere activar marketing_config y la migracion 052" } },
  { id: "restaurantes.whatsapp.silencio", ambito: "restaurantes", categoria: "salud", severidad: "atencion", roles: [], icono: "PhoneOff", titulo: "WhatsApp está en silencio: no llegan mensajes", cuerpo: "Normalmente a esta hora llegan unos {mensajes} mensajes cada {ventana} minutos y no ha llegado ninguno. Revise que el número y la conexión de WhatsApp sigan activos en Configuración.", parametros: ["mensajes", "ventana"], enlace: "/restaurantes/{orgSlug}/configuracion", dedupe: "una por organizacion por dia (clave = fecha de Merida)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/alertas-duenio/silencio.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min): 0 mensajes entrantes en la ventana (60 min por omision) cuando el mismo dia y hora de las 4 semanas previas promediaron 3 o mas; el horario de servicio se infiere del historico; umbrales por organizacion en alertas_duenio_config; requiere la migracion 052" } },
  { id: "restaurantes.ia.presupuesto_umbral", ambito: "restaurantes", categoria: "cierres", severidad: "atencion", roles: [], icono: "Gauge", titulo: "El presupuesto de IA llegó al {porcentaje} por ciento este mes", cuerpo: "Al llegar al 100 por ciento el agente deja de responder con IA hasta el siguiente mes o hasta que se amplíe el presupuesto de la organización.", parametros: ["porcentaje"], enlace: "/restaurantes/{orgSlug}/configuracion", dedupe: "una por umbral (80, 100) por mes de Merida", venceDias: 31, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/alertas-duenio/presupuesto.ts", nota: "sale desde la reserva mensual de IA (apps/api/src/production/llm-usage-gateway-adapters.ts) al 80 por ciento y al agotarse el tope; solo organizaciones de restaurantes; requiere la migracion 052 (es_organizacion_restaurantes)" } },
  { id: "restaurantes.demo.tope_diario_alcanzado", ambito: "restaurantes", categoria: "cierres", severidad: "atencion", roles: [], icono: "Gauge", titulo: "La demo alcanzó su tope diario de mensajes", cuerpo: "Tope de hoy: {cantidad} mensajes. El chat de la demo responde \"tope alcanzado\" hasta mañana.", parametros: ["cantidad"], enlace: "/restaurantes/{orgSlug}/configuracion", dedupe: "una por dia", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/demo-widget.ts" } },
  { id: "restaurantes.voz.tope_notas_alcanzado", ambito: "restaurantes", categoria: "cierres", severidad: "atencion", roles: [], icono: "Gauge", titulo: "Las notas de voz de WhatsApp alcanzaron su tope del día", cuerpo: "Tope de hoy: {cantidad} notas. Las siguientes se atienden pidiéndole al cliente que escriba su mensaje.", parametros: ["cantidad"], enlace: "/restaurantes/{orgSlug}/configuracion", dedupe: "una por dia", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/whatsapp.ts", nota: "tope de costo de transcripcion por organizacion (R-32)" } },
  { id: "restaurantes.costo.umbral_voz", ambito: "restaurantes", categoria: "cierres", severidad: "atencion", roles: [], icono: "Gauge", titulo: "El costo de voz del día alcanzó el umbral configurado", cuerpo: "Revise el consumo de la sucursal en Agente de voz.", parametros: [], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por sucursal por dia", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/voz-kpi.ts", nota: "depende de accion manual: sale cuando alguien evalua las alertas (POST .../alertas/evaluar), no hay cron" } },
  { id: "restaurantes.voz.tasa_error_alta", ambito: "restaurantes", categoria: "salud", severidad: "atencion", roles: [], icono: "TriangleAlert", titulo: "La tasa de errores del agente de voz superó el umbral configurado", cuerpo: "Revise el estado del servicio de voz en Indicadores.", parametros: [], enlace: "/restaurantes/{orgSlug}/agente-voz", dedupe: "una por sucursal por dia", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/voz-kpi.ts", nota: "depende de accion manual: sale cuando alguien evalua las alertas (POST .../alertas/evaluar), no hay cron" } },
  { id: "restaurantes.onboarding.listo", ambito: "restaurantes", categoria: "onboarding", severidad: "info", roles: [], icono: "CircleCheckBig", titulo: "Primeros pasos completos: el restaurante está listo para operar", cuerpo: null, parametros: [], enlace: "/restaurantes/{orgSlug}/primeros-pasos", dedupe: "una por organizacion, al completarse el ultimo punto obligatorio (no al leer el checklist)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/onboarding-aviso.ts", nota: "se emite en la escritura que lo completa: disponibilidad de menu por sucursal, politica/horario de sucursal o configuracion del agente" } },
  { id: "restaurantes.cierre.dia_listo", ambito: "restaurantes", categoria: "cierres", severidad: "info", roles: [], icono: "ReceiptText", titulo: "Cierre del día {fecha} listo", cuerpo: "Pedidos: {pedidos}. Ventas: {ventas} MXN.", parametros: ["fecha", "pedidos", "ventas"], enlace: "/restaurantes/{orgSlug}/cierres", dedupe: "una por sucursal por dia de negocio (clave = sucursal + fecha); reintentar el cierre no repite el aviso", venceDias: 14, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/cierres/barrido.ts", nota: "sale al generar el cierre (boton del panel o POST /internal/restaurantes/cierres-dia); no hay cron en vercel.json (decision de costo): hasta que alguien agende el endpoint, solo sale con el boton" } },
  { id: "restaurantes.cierre.semana_lista", ambito: "restaurantes", categoria: "cierres", severidad: "info", roles: [], icono: "CalendarRange", titulo: "Resumen de la semana del {fecha} listo", cuerpo: "Pedidos: {pedidos}. Ventas: {ventas} MXN.", parametros: ["fecha", "pedidos", "ventas"], enlace: "/restaurantes/{orgSlug}/cierres", dedupe: "una por sucursal por semana (clave = sucursal + lunes de la semana)", venceDias: 30, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/cierres/barrido.ts", nota: "mismo productor y misma limitacion de cron que el cierre del dia" } },
  { id: "restaurantes.aprobacion.pedido_grande", ambito: "restaurantes", categoria: "aprobaciones", severidad: "atencion", roles: ["staff"], icono: "ShieldCheck", titulo: "Un pedido grande espera su aprobación", cuerpo: "Revise la pestaña Por aprobar: apruebe o rechace con un clic. Nunca se aprueba solo.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por solicitud (clave = id de la solicitud)", venceDias: 3, productor: { estado: "pendiente", motivo: "El productor existe y esta probado (packages/domain-restaurantes/src/autopiloto/servicio.ts) pero nadie lo invoca aun: requiere cablear el agente de WhatsApp y voz sobre B2 y B1 (PR 421 y 424), que `crear_pedido` llame a `retenerPedidoGrande` al detectar un pedido grande" } },
  { id: "restaurantes.aprobacion.cancelacion", ambito: "restaurantes", categoria: "aprobaciones", severidad: "atencion", roles: ["staff"], icono: "CircleX", titulo: "Un cliente pide cancelar un pedido en proceso", cuerpo: "Decida con un clic si se cancela o se mantiene en Por aprobar.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por solicitud (clave = id de la solicitud)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/autopiloto/servicio.ts", nota: "sale cuando el agente de WhatsApp recibe una cancelacion con la bandera de la organizacion encendida (Reglas del autopiloto, apagada por omision); la voz todavia no" } },
  { id: "restaurantes.aprobacion.compensacion", ambito: "restaurantes", categoria: "aprobaciones", severidad: "atencion", roles: ["staff"], icono: "HandCoins", titulo: "Una queja espera su decisión de compensación", cuerpo: "Elija sin compensación, reponer producto o descuento en el próximo pedido.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por solicitud (clave = id de la solicitud)", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/autopiloto/servicio.ts", nota: "sale cuando el clasificador de WhatsApp detecta una queja y el cliente tiene un pedido reciente entregado; la voz todavia no" } },
  { id: "restaurantes.aprobacion.vencida", ambito: "restaurantes", categoria: "aprobaciones", severidad: "critica", roles: [], icono: "AlarmClock", titulo: "Una aprobación lleva {minutos} minutos sin respuesta", cuerpo: "Revise Por aprobar en Pedidos. El sistema nunca aprueba solo.", parametros: ["minutos"], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por solicitud (clave = id de la solicitud); solo owner/admin", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/autopiloto/servicio.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min)" } },
  { id: "restaurantes.pedido.cancelado_por_cliente", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "Ban", titulo: "Un cliente canceló su pedido antes de cocina", cuerpo: "La cancelación automática de la sucursal lo canceló; no hace falta prepararlo.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por pedido (clave = id del pedido)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/autopiloto/servicio.ts", nota: "solo con la bandera de la organizacion y la cancelacion automatica de la sucursal encendidas (ambas apagadas por omision), pedido sin comanda en el POS" } },
  { id: "restaurantes.pedido.no_recogido", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "PackageX", titulo: "Un pedido para recoger no fue recogido a tiempo", cuerpo: "Quedó como no recogido; revise Pedidos para decidir qué hacer con él.", parametros: [], enlace: "/restaurantes/{orgSlug}/pedidos", dedupe: "una por pedido (clave = id del pedido)", venceDias: 2, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/autopiloto/servicio.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min); no se avisa al cliente" } },
  { id: "restaurantes.handoff.devuelto_automatico", ambito: "restaurantes", categoria: "agentes", severidad: "info", roles: ["staff"], icono: "Undo2", titulo: "Una conversación volvió al agente por falta de respuesta", cuerpo: "Pasaron {minutos} minutos sin respuesta humana; el agente retomó la conversación.", parametros: ["minutos"], enlace: "/restaurantes/{orgSlug}/conversaciones", dedupe: "una por toma (clave = id del handoff)", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/autopiloto/servicio.ts", nota: "sale en el tick /internal/restaurantes/promover-programados (cada 5 min)" } },
  { id: "restaurantes.repartidor.licencia_por_vencer", ambito: "restaurantes", categoria: "operacion", severidad: "atencion", roles: [], icono: "IdCard", titulo: "La licencia de un repartidor vence en {dias} días", cuerpo: "Revise el perfil del repartidor en Staff.", parametros: ["dias"], enlace: "/restaurantes/{orgSlug}/staff", dedupe: "una por repartidor por mes", venceDias: 30, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/repartidor-perfil/notificar.ts", nota: "sale al guardar el perfil con la licencia a menos de 30 dias y en el barrido POST /internal/restaurantes/repartidor-licencias; no hay cron en vercel.json (decision de costo): hasta que alguien agende el endpoint, solo sale al guardar el perfil" } },
  { id: "restaurantes.repartidor.licencia_vencida", ambito: "restaurantes", categoria: "operacion", severidad: "critica", roles: [], icono: "IdCard", titulo: "La licencia de un repartidor venció hace {dias} días", cuerpo: "Revise el perfil del repartidor en Staff antes de asignarle pedidos.", parametros: ["dias"], enlace: "/restaurantes/{orgSlug}/staff", dedupe: "una por repartidor por mes", venceDias: 30, productor: { estado: "conectado", archivo: "packages/domain-restaurantes/src/repartidor-perfil/notificar.ts", nota: "mismo productor y misma limitacion de cron que la licencia por vencer" } },
  { id: "restaurantes.agente.whatsapp_apagado", ambito: "restaurantes", categoria: "agentes", severidad: "atencion", roles: ["staff"], icono: "PowerOff", titulo: "El agente de WhatsApp de una sucursal quedó apagado", cuerpo: "Los mensajes de esa sucursal ya no los atiende el agente: llegan a la bandeja de Conversaciones para que una persona los conteste.", parametros: [], enlace: "/restaurantes/{orgSlug}/conversaciones", dedupe: "una por sucursal por dia (clave = id de la sucursal y fecha UTC)", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/restaurantes/admin-conocimiento.ts" } },
  // ---- Hoteles ------------------------------------------------------------------------------------
  { id: "hoteles.ticket.sla_vencido", ambito: "hoteles", categoria: "operacion", severidad: "atencion", roles: ["gm", "frontdesk"], icono: "Clock", titulo: "Tickets de huéspedes con SLA vencido", cuerpo: "Escalados: {cantidad}.", parametros: ["cantidad"], enlace: "/hoteles/{orgSlug}/tickets", dedupe: "una por propiedad por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/tickets-sla-cron.ts" } },
  { id: "hoteles.aprobacion.expirada", ambito: "hoteles", categoria: "aprobaciones", severidad: "atencion", roles: ["gm", "reservations"], icono: "ShieldAlert", titulo: "Solicitudes del agente expiraron sin decisión", cuerpo: "Expiradas: {cantidad}.", parametros: ["cantidad"], enlace: "/hoteles/{orgSlug}/aprobaciones", dedupe: "una por propiedad por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/agentes-expiracion-cron.ts" } },
  { id: "hoteles.aprobacion.pendiente", ambito: "hoteles", categoria: "aprobaciones", severidad: "atencion", roles: ["gm", "reservations"], icono: "ShieldCheck", titulo: "Hay una solicitud del agente por aprobar", cuerpo: null, parametros: [], enlace: "/hoteles/{orgSlug}/aprobaciones", dedupe: "una por solicitud", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-hoteles/src/agentes/postgres-repository.ts" } },
  { id: "hoteles.conversacion.handoff", ambito: "hoteles", categoria: "agentes", severidad: "atencion", roles: ["frontdesk", "reservations"], icono: "UserRoundCog", titulo: "Un huésped necesita a una persona en WhatsApp", cuerpo: "El agente derivó una conversación: tómala desde Conversaciones.", parametros: [], enlace: "/hoteles/{orgSlug}/conversaciones", dedupe: "una por conversacion derivada (clave = id de la conversacion + numero de derivacion)", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-hoteles/src/conversaciones/postgres-repository.ts", nota: "se emite cuando el agente pide una persona o el gobierno lo bloquea (pausado o sin presupuesto); los mensajes nuevos con la conversacion ya en humano solo suman no leidos en la bandeja" } },
  { id: "hoteles.grupo.por_liberar", ambito: "hoteles", categoria: "cierres", severidad: "atencion", roles: ["gm", "reservations"], icono: "Users", titulo: "Bloqueos de grupo por liberar", cuerpo: "Grupos: {cantidad}.", parametros: ["cantidad"], enlace: "/hoteles/{orgSlug}/grupos", dedupe: "una por propiedad por dia", venceDias: 5, productor: { estado: "pendiente", motivo: "cron grupos-liberacion: falta decidir el umbral de aviso con producto" } },
  { id: "hoteles.grupo.liberado", ambito: "hoteles", categoria: "cierres", severidad: "atencion", roles: ["gm", "reservations"], icono: "Users", titulo: "Se liberaron bloqueos de grupo por su fecha de corte", cuerpo: "Bloqueos liberados: {cantidad}.", parametros: ["cantidad"], enlace: "/hoteles/{orgSlug}/grupos", dedupe: "una por propiedad por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/grupos-liberacion-cron.ts" } },
  { id: "hoteles.lista_espera.disponible", ambito: "hoteles", categoria: "operacion", severidad: "atencion", roles: ["gm", "frontdesk", "reservations"], icono: "Hourglass", titulo: "Se liberó lugar para una entrada de la lista de espera", cuerpo: "La entrada quedó ofrecida y vence pronto: contacta a la persona desde Reservas, pestaña Lista de espera.", parametros: [], enlace: "/hoteles/{orgSlug}/reservas", dedupe: "una por entrada ofrecida (clave = id de la entrada)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/lista-espera-ofertas.ts", nota: "se emite al cancelar una reserva o acortar fechas y encontrar una entrada compatible; el aviso al huesped por WhatsApp no esta conectado (depende de Meta, H-23)" } },
  { id: "hoteles.night_audit.fallo", ambito: "hoteles", categoria: "cierres", severidad: "critica", roles: ["gm", "accountant"], icono: "MoonStar", titulo: "El cierre nocturno no terminó", cuerpo: null, parametros: [], enlace: "/hoteles/{orgSlug}/reservas", dedupe: "una por propiedad por noche", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/night-audit.ts" } },
  { id: "hoteles.housekeeping.inspeccion_rechazada", ambito: "hoteles", categoria: "operacion", severidad: "atencion", roles: ["gm", "frontdesk", "housekeeping"], icono: "ClipboardX", titulo: "Una inspección de limpieza fue rechazada", cuerpo: "La habitación vuelve a la cola de limpieza.", parametros: [], enlace: "/hoteles/{orgSlug}/housekeeping", dedupe: "una por tarea y por rechazo", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/housekeeping.ts" } },
  { id: "hoteles.housekeeping.dia_generado", ambito: "hoteles", categoria: "automatizaciones", severidad: "info", roles: ["gm", "frontdesk", "housekeeping"], icono: "ClipboardList", titulo: "Arrancó el día de limpieza", cuerpo: "Tareas generadas: {generadas}. Sin asignar: {sinAsignar}.", parametros: ["generadas", "sinAsignar"], enlace: "/hoteles/{orgSlug}/housekeeping", dedupe: "una por propiedad por dia", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/housekeeping-dia-cron.ts" } },
  { id: "hoteles.housekeeping.sin_cupo", ambito: "hoteles", categoria: "operacion", severidad: "atencion", roles: ["gm", "frontdesk"], icono: "UsersRound", titulo: "Tareas de limpieza sin camarista con cupo", cuerpo: "Tareas sin asignar: {cantidad}.", parametros: ["cantidad"], enlace: "/hoteles/{orgSlug}/housekeeping", dedupe: "una por propiedad por dia", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/housekeeping-residual.ts", nota: "tambien la emite el arranque automatico del dia (housekeeping-dia-cron.ts) cuando la asignacion automatica deja tareas sin camarista" } },
  { id: "hoteles.tarifa.aplicacion_rechazada", ambito: "hoteles", categoria: "operacion", severidad: "atencion", roles: ["gm"], icono: "Gauge", titulo: "Una tarifa aprobada no se pudo aplicar", cuerpo: "Aprobadas rechazadas por la guarda del motor: {cantidad}. Revísalas en Revenue.", parametros: ["cantidad"], enlace: "/hoteles/{orgSlug}/revenue", dedupe: "una por propiedad por dia", venceDias: 5, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/revenue-recommendations-cron.ts" } },
  { id: "hoteles.canal.whatsapp_actualizado", ambito: "hoteles", categoria: "seguridad", severidad: "atencion", roles: ["gm"], icono: "MessageSquareLock", titulo: "Se cambió el número de WhatsApp de la propiedad", cuerpo: "Revisa que sea el número correcto del hotel.", parametros: [], enlace: "/hoteles/{orgSlug}/mensajeria", dedupe: "una por propiedad por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/mensajeria-config.ts" } },
  { id: "hoteles.arco.solicitud_publica", ambito: "hoteles", categoria: "operacion", severidad: "atencion", roles: ["gm"], icono: "ShieldAlert", titulo: "Llegó una solicitud ARCO verificada por el titular", cuerpo: "Revísala en Identidad, pestaña Privacidad: el plazo de respuesta ya corre.", parametros: [], enlace: "/hoteles/{orgSlug}/identidad", dedupe: "una por solicitud (clave = id)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/hoteles/privacidad-publica.ts", nota: "se emite cuando el titular confirma el codigo de su correo (la solicitud publica pasa de pendiente_verificacion a recibida)" } },
  // ---- Rentas vacacionales ------------------------------------------------------------------------
  { id: "rentas.ical.sync_fallido", ambito: "rentas", categoria: "salud", severidad: "critica", roles: ["admin_gestora", "operador:acceso_total"], icono: "RefreshCwOff", titulo: "Falla la sincronización de calendarios", cuerpo: "Calendarios con error: {cantidad}.", parametros: ["cantidad"], enlace: "/rentas/{orgSlug}/monitor-sync", dedupe: "una por property por dia (clave = property + dia)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/ical-sync-cron.ts" } },
  { id: "rentas.reserva.nueva_ical", ambito: "rentas", categoria: "operacion", severidad: "info", roles: ["admin_gestora", "operador:acceso_total", "operador:calendario_mensajeria"], icono: "CalendarPlus", titulo: "Reservas nuevas importadas del calendario", cuerpo: "Nuevas: {cantidad}.", parametros: ["cantidad"], enlace: "/rentas/{orgSlug}/calendario", dedupe: "una por property por dia (clave = property + dia)", venceDias: 5, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/ical-sync-cron.ts" } },
  { id: "rentas.conflicto.detectado", ambito: "rentas", categoria: "operacion", severidad: "critica", roles: ["admin_gestora", "operador:acceso_total"], icono: "CalendarX", titulo: "Hay reservas en conflicto", cuerpo: "Conflictos: {cantidad}.", parametros: ["cantidad"], enlace: "/rentas/{orgSlug}/calendario", dedupe: "una por property por dia (clave = property + dia)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/ical-sync-cron.ts" } },
  { id: "rentas.aprobacion.pendiente", ambito: "rentas", categoria: "aprobaciones", severidad: "atencion", roles: ["admin_gestora", "operador:calendario_mensajeria"], icono: "MessageSquareWarning", titulo: "Un mensaje a huésped espera aprobación", cuerpo: null, parametros: [], enlace: "/rentas/{orgSlug}/aprobaciones", dedupe: "una por mensaje", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/mensajeria-borradores.ts" } },
  { id: "rentas.aprobacion.urgente", ambito: "rentas", categoria: "aprobaciones", severidad: "critica", roles: ["admin_gestora", "operador:calendario_mensajeria"], icono: "Siren", titulo: "Un mensaje a huésped requiere atención humana", cuerpo: "El borrador detectó una queja, emergencia, reembolso o trato VIP: revísalo primero.", parametros: [], enlace: "/rentas/{orgSlug}/aprobaciones/{entidadId}", dedupe: "una por borrador (clave = id del borrador; se emite en lugar de rentas.aprobacion.pendiente)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/mensajeria-borradores.ts", nota: "entidadId = id de la conversacion" } },
  { id: "rentas.limpieza.tarea_asignada", ambito: "rentas", categoria: "operacion", severidad: "info", roles: ["limpieza"], icono: "ClipboardCheck", titulo: "Hay una tarea de limpieza asignada", cuerpo: null, parametros: [], enlace: "/rentas/{orgSlug}/mis-tareas", dedupe: "una por tarea y persona asignada (clave = tarea + persona)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/limpieza-avisos.ts", nota: "llega a owner/admin y a todo el rol limpieza de la propiedad, no solo a quien recibe la tarea (core.emit_notification no admite destinatario)" } },
  { id: "rentas.limpieza.sin_asignar", ambito: "rentas", categoria: "operacion", severidad: "atencion", roles: ["admin_gestora", "operador:acceso_total"], icono: "UserX", titulo: "Hay tareas de limpieza de mañana sin responsable", cuerpo: "Tareas sin responsable: {cantidad}.", parametros: ["cantidad"], enlace: "/rentas/{orgSlug}/mis-tareas", dedupe: "una por propiedad por dia de la tarea (clave = propiedad + dia)", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/limpieza-avisos.ts" } },
  { id: "rentas.privacidad.arco_registrada", ambito: "rentas", categoria: "seguridad", severidad: "atencion", roles: ["admin_gestora"], icono: "ShieldAlert", titulo: "Hay una solicitud ARCO por atender", cuerpo: null, parametros: [], enlace: "/rentas/{orgSlug}/privacidad", dedupe: "una por solicitud", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/rentas/privacidad.ts" } },
  { id: "rentas.privacidad.arco_por_vencer", ambito: "rentas", categoria: "seguridad", severidad: "critica", roles: ["admin_gestora"], icono: "CalendarClock", titulo: "Solicitudes ARCO por vencer o vencidas", cuerpo: "Solicitudes: {cantidad}.", parametros: ["cantidad"], enlace: "/rentas/{orgSlug}/privacidad", dedupe: "una por organizacion por dia (clave = organizacion + dia)", venceDias: 7, productor: { estado: "pendiente", motivo: "Requiere un cron diario que revise los plazos de las solicitudes abiertas; no se agenda en este PR (decision de costo, igual que la purga PL-13)." } },
  // ---- Despachos contables ------------------------------------------------------------------------
  { id: "despachos.cobranza.recordatorios", ambito: "despachos", categoria: "cobranza", severidad: "atencion", roles: ["contador"], icono: "Receipt", titulo: "Cuentas por cobrar con recordatorio hoy", cuerpo: "Cuentas con recordatorio: {cantidad}.", parametros: ["cantidad"], enlace: "/despachos/{orgSlug}/cola-cobranza", dedupe: "una por organizacion por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/notifications.ts" } },
  { id: "despachos.fiscal.vencimiento_proximo", ambito: "despachos", categoria: "fiscal", severidad: "atencion", roles: ["contador"], icono: "CalendarClock", titulo: "Obligaciones fiscales por vencer", cuerpo: "Por vencer hoy o mañana: {cantidad}.", parametros: ["cantidad"], enlace: "/despachos/{orgSlug}/vencimientos", dedupe: "una por property por dia", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-despachos/src/vencimientos/procesos.ts", nota: "lo dispara el boton del panel y el cron diario /internal/despachos/vencimientos-barrido (D-26)" } },
  { id: "despachos.fiscal.vencimiento_vencido", ambito: "despachos", categoria: "fiscal", severidad: "critica", roles: ["contador"], icono: "CalendarX", titulo: "Obligaciones fiscales vencidas", cuerpo: "Vencidas sin presentar: {cantidad}.", parametros: ["cantidad"], enlace: "/despachos/{orgSlug}/vencimientos", dedupe: "una por property por dia", venceDias: 14, productor: { estado: "conectado", archivo: "packages/domain-despachos/src/vencimientos/procesos.ts", nota: "lo dispara el boton del panel y el cron diario /internal/despachos/vencimientos-barrido (D-26)" } },
  { id: "despachos.fiscal.vencimiento_escalado", ambito: "despachos", categoria: "fiscal", severidad: "atencion", roles: ["contador"], icono: "ArrowUpFromLine", titulo: "Se escaló una obligación fiscal", cuerpo: "Nivel de escalamiento: {nivel}.", parametros: ["nivel"], enlace: "/despachos/{orgSlug}/vencimientos", dedupe: "una por vencimiento y nivel", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/vencimientos.ts", nota: "depende de accion manual: sale al escalar a mano un vencimiento desde el panel, no hay cron" } },
  { id: "despachos.rep.incoherente", ambito: "despachos", categoria: "fiscal", severidad: "atencion", roles: ["contador", "auditor"], icono: "FileWarning", titulo: "Un complemento de pago tiene documentos sin ligar o con saldo incoherente", cuerpo: "Documentos a revisar: {cantidad}.", parametros: ["cantidad"], enlace: "/despachos/{orgSlug}/cfdi", dedupe: "una por complemento de pago guardado (clave = property + folio fiscal del REP)", venceDias: 14, productor: { estado: "pendiente", motivo: "el analisis de REP (POST .../cfdi/rep/analizar) no guarda nada y lo pueden llamar roles de solo lectura: emitir ahi llenaria la campana con XML arbitrario; se conecta cuando el REP se persista" } },
  { id: "despachos.efos.alerta", ambito: "despachos", categoria: "fiscal", severidad: "critica", roles: ["contador", "auditor"], icono: "ShieldAlert", titulo: "Se ingirió un CFDI de un emisor presunto o definitivo en la lista 69-B", cuerpo: null, parametros: [], enlace: "/despachos/{orgSlug}/cfdi", dedupe: "una por CFDI ingerido (clave = id del CFDI)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/cfdi.ts", nota: "tambien lo emite el cron mensual /internal/despachos/efos-69b/descarga, apps/api/src/routes/verticals/despachos/cron-sat.ts, con la misma clave: un CFDI no se avisa dos veces" } },
  { id: "despachos.cfdi.lote_importado", ambito: "despachos", categoria: "fiscal", severidad: "info", roles: ["contador"], icono: "FileStack", titulo: "Se importó un lote de CFDI", cuerpo: "Ingeridos: {ingeridos}; en revisión: {en_revision}; duplicados: {duplicados}; rechazados: {rechazados}.", parametros: ["ingeridos", "en_revision", "duplicados", "rechazados"], enlace: "/despachos/{orgSlug}/cfdi", dedupe: "una por lote importado (clave = identificador aleatorio del lote, generado por la peticion)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/cfdi-lote.ts", nota: "POST .../cfdi/importar-lote (carga masiva de XML o ZIP, D-13): una por peticion con al menos un CFDI o REP nuevo; no se emite si todo fue duplicado o rechazado" } },
  { id: "despachos.cfdi.cancelado", ambito: "despachos", categoria: "fiscal", severidad: "critica", roles: ["contador"], icono: "FileX", titulo: "Un CFDI fue cancelado ante el SAT", cuerpo: "Un comprobante que estaba vigente aparece cancelado. Revisa su tratamiento fiscal.", parametros: [], enlace: "/despachos/{orgSlug}/cfdi/{entidadId}", dedupe: "una por CFDI (clave = id del CFDI; la cancelacion es terminal)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/cfdi-estatus-sat.ts", nota: "tambien lo emite el cron semanal de estatus SAT (apps/worker/src/jobs/despachos/cfdi-estatus-sat.ts, via cron-sat.ts); el mismo CFDI no se avisa dos veces" } },
  { id: "despachos.pago_provisional.por_vencer", ambito: "despachos", categoria: "fiscal", severidad: "atencion", roles: ["contador"], icono: "CalendarClock", titulo: "Pagos provisionales de ISR o IVA por vencer", cuerpo: "Por vencer en los próximos 3 días: {cantidad}.", parametros: ["cantidad"], enlace: "/despachos/{orgSlug}/pagos-provisionales", dedupe: "una por organizacion por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/pagos-provisionales-aviso.ts" } },
  { id: "despachos.conciliacion.sugerencias_pendientes", ambito: "despachos", categoria: "aprobaciones", severidad: "atencion", roles: ["contador"], icono: "Sparkles", titulo: "Hay sugerencias de IA de conciliación bancaria por revisar", cuerpo: "Sugerencias pendientes de aprobar o rechazar: {cantidad}.", parametros: ["cantidad"], enlace: "/despachos/{orgSlug}/conciliacion", dedupe: "una por sesion de conciliacion (clave = id de la sesion)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/despachos/conciliacion-persistida.ts" } },
  // ---- Licitaciones -------------------------------------------------------------------------------
  { id: "licitaciones.plazo.por_vencer", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "writer", "reviewer"], icono: "Hourglass", titulo: "Convocatorias con plazo por vencer", cuerpo: "Recordatorios nuevos: {cantidad}.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/seguimiento", dedupe: "una por organizacion por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/discover.ts" } },
  { id: "licitaciones.convocatoria.nueva", ambito: "licitaciones", categoria: "operacion", severidad: "info", roles: ["analyst"], icono: "FilePlus2", titulo: "La ingesta automática descubrió licitaciones nuevas", cuerpo: "Registros nuevos: {cantidad}.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/convocatorias", dedupe: "una por organizacion por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/discover.ts" } },
  { id: "licitaciones.fallo.publicado", ambito: "licitaciones", categoria: "cierres", severidad: "atencion", roles: ["analyst", "reviewer"], icono: "Gavel", titulo: "Se publico un fallo", cuerpo: null, parametros: [], enlace: "/licitaciones/{orgSlug}/seguimiento", dedupe: "una por convocatoria", venceDias: 30, productor: { estado: "pendiente", motivo: "requiere el detector de fallo en la fuente (depende de un agregador comercial sin proveedor elegido)" } },
  { id: "licitaciones.expediente.aprobacion_pendiente", ambito: "licitaciones", categoria: "aprobaciones", severidad: "atencion", roles: ["analyst"], icono: "ShieldCheck", titulo: "Un expediente espera la aprobación económica (2/2)", cuerpo: "La aprobación técnico-legal ya se dio; la económica debe darla otra persona.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias", dedupe: "una por propuesta y estado de insumos (clave = id de la propuesta + prefijo del hash de insumos)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/cierre.ts" } },
  { id: "licitaciones.expediente.aprobado", ambito: "licitaciones", categoria: "cierres", severidad: "info", roles: ["analyst", "writer"], icono: "CircleCheckBig", titulo: "Expediente aprobado (2/2): ya se puede ensamblar el paquete", cuerpo: null, parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias", dedupe: "una por propuesta y estado de insumos (clave = id de la propuesta + prefijo del hash de insumos)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/cierre.ts" } },
  { id: "licitaciones.presentacion.declarada", ambito: "licitaciones", categoria: "cierres", severidad: "info", roles: ["analyst", "reviewer"], icono: "FileCheck2", titulo: "Se declaró la presentación de un expediente ante el portal", cuerpo: "Atiende no envía ofertas: solo registró la declaración de una persona de tu equipo.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias", dedupe: "una por propuesta (clave = id de la propuesta)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/cierre.ts" } },
  { id: "licitaciones.sala_guerra.paquete_no_listo", ambito: "licitaciones", categoria: "cierres", severidad: "critica", roles: ["analyst", "writer", "reviewer"], icono: "TimerReset", titulo: "A menos de 24 horas del cierre, un paquete de licitación no está listo", cuerpo: "Abre la sala de guerra de la convocatoria: el gate final muestra qué condición falta (aprobación, checklist, paquete o ZIP).", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias", dedupe: "una por convocatoria (clave = id de la convocatoria)", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/salaGuerra.ts" } },
  { id: "licitaciones.renovacion.por_vencer", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst"], icono: "CalendarClock", titulo: "Contratos con renovación por vencer", cuerpo: "Alertas de renovación nuevas: {cantidad}.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/radar-renovaciones", dedupe: "una por organizacion por dia (solo cuando el barrido creo alertas nuevas)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale del barrido /internal/licitaciones/alert-notifications (cron existente de vercel.json)" } },
  { id: "licitaciones.cobranza.factura_vencida", ambito: "licitaciones", categoria: "cobranza", severidad: "atencion", roles: ["analyst"], icono: "Receipt", titulo: "Facturas de contratos vencidas sin cobrar", cuerpo: "Facturas vencidas: {cantidad}.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/radar-renovaciones", dedupe: "una por organizacion por semana (mientras sigan vencidas)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale del barrido /internal/licitaciones/alert-notifications (cron existente de vercel.json)" } },
  { id: "licitaciones.convocatoria.bases_modificadas", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "writer", "reviewer"], icono: "FileDiff", titulo: "Cambiaron las bases de una convocatoria que el equipo ya versionó", cuerpo: "Revisa el cambio en Seguimiento: puede invalidar secciones ya redactadas.", parametros: [], enlace: "/licitaciones/{orgSlug}/seguimiento", dedupe: "una por convocatoria y version (clave = id de la convocatoria + numero de version)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "se emite en la escritura que crea la nueva version (alta manual, recalculo y re-extraccion de requisitos), nunca en una lectura" } },
  { id: "licitaciones.documentos.por_vencer", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "writer"], icono: "FileClock", titulo: "Documentos de la empresa por vencer en los próximos 30 días", cuerpo: "Documentos aprobados por vencer (incluye la opinión 32-D si está registrada): {cantidad}.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/datos-empresa", dedupe: "una por organizacion por semana (mientras haya documentos por vencer)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale del barrido /internal/licitaciones/alert-notifications; requiere la migracion 034 (sin ella no emite)" } },
  { id: "licitaciones.datos_empresa.aprobacion_pendiente", ambito: "licitaciones", categoria: "aprobaciones", severidad: "atencion", roles: ["analyst"], icono: "ShieldCheck", titulo: "Un dato de empresa espera aprobación", cuerpo: "Alguien propuso o editó una tarifa, documento, capacidad, experiencia o firmante: lo debe decidir otra persona con rol de decisión.", parametros: [], enlace: "/licitaciones/{orgSlug}/datos-empresa", dedupe: "una por dato y hora (clave = tipo + id del dato + hora)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/companyData.ts", nota: "se emite al crear o editar un dato de empresa (queda pendiente de aprobacion)" } },
  { id: "licitaciones.kyc.proveedor_empeoro", ambito: "licitaciones", categoria: "fiscal", severidad: "critica", roles: ["analyst", "reviewer"], icono: "ShieldAlert", titulo: "Un proveedor de tu cartera pasó a presunto o definitivo en la lista 69-B", cuerpo: "Proveedores cuyo semáforo empeoró en la edición nueva: {cantidad}.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/kyc-69b", dedupe: "una por organizacion y edicion de la lista (clave = organizacion + periodo)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale de POST /internal/licitaciones/kyc-69b/retamizar (ruta interna idempotente; sin cron en vercel.json, la invoca quien ingiere la lista); requiere la migracion 034" } },
  { id: "licitaciones.contrato.garantia_por_vencer", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "reviewer"], icono: "ShieldAlert", titulo: "Una garantía de un contrato vence en los próximos 30 días", cuerpo: "Abre Post-adjudicación: renueva la fianza o libera la garantía antes de que termine su vigencia.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias/{entidadId}/post-adjudicacion", dedupe: "una por garantia y fecha de fin de vigencia (clave = id de la garantia + fecha)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale del barrido /internal/licitaciones/alert-notifications (cron existente de vercel.json); requiere la migracion 035 (sin ella no emite)" } },
  { id: "licitaciones.contrato.garantia_no_entregada", ambito: "licitaciones", categoria: "operacion", severidad: "critica", roles: ["analyst", "reviewer"], icono: "FileWarning", titulo: "Una garantía de un contrato no se entregó dentro de su plazo", cuerpo: "Abre Post-adjudicacion: la fecha limite de entrega ya paso y la garantia sigue pendiente.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias/{entidadId}/post-adjudicacion", dedupe: "una por garantia y fecha limite de entrega (clave = id de la garantia + fecha)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale del barrido /internal/licitaciones/alert-notifications (cron existente de vercel.json); requiere la migracion 035 (sin ella no emite)" } },
  { id: "licitaciones.contrato.hito_vencido", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "writer", "reviewer"], icono: "ListChecks", titulo: "Un hito de un contrato pasó su fecha comprometida", cuerpo: "Abre Post-adjudicacion: el hito sigue pendiente. Su responsable puede marcarlo cumplido o reprogramarlo.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias/{entidadId}/post-adjudicacion", dedupe: "una por hito y fecha comprometida (clave = id del hito + fecha)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-campana.ts", nota: "sale del barrido /internal/licitaciones/alert-notifications (cron existente de vercel.json); requiere la migracion 035 (sin ella no emite)" } },
  { id: "licitaciones.revision.solicitada", ambito: "licitaciones", categoria: "aprobaciones", severidad: "atencion", roles: ["analyst", "reviewer"], icono: "ClipboardCheck", titulo: "Se pidió la revisión de un expediente", cuerpo: "Abre Aprobaciones: hay un expediente o una sección esperando revisión.", parametros: [], enlace: "/licitaciones/{orgSlug}/aprobaciones", dedupe: "una por solicitud (clave = id de la solicitud de revision)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-revision.ts", nota: "se emite al registrar la solicitud de revision (POST .../proposal/request-review); requiere la migracion 037" } },
  { id: "licitaciones.requisitos.conflicto_abierto", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "writer", "reviewer"], icono: "FileWarning", titulo: "Hay conflictos entre los documentos de las bases que requieren una decisión", cuerpo: "Conflictos abiertos: {cantidad}. Mientras sigan abiertos, el checklist del expediente no puede quedar en verde.", parametros: ["cantidad"], enlace: "/licitaciones/{orgSlug}/convocatorias/{entidadId}/requisitos", dedupe: "una por convocatoria y conjunto de conflictos abiertos (clave = id de la convocatoria + huella de los ids)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-revision.ts", nota: "se emite al extraer requisitos cuando quedan conflictos abiertos; requiere la migracion 037" } },
  { id: "licitaciones.documentos.sin_texto", ambito: "licitaciones", categoria: "operacion", severidad: "atencion", roles: ["analyst", "writer"], icono: "FileWarning", titulo: "Un documento de las bases no se pudo leer", cuerpo: "Suba una versión con texto (PDF no escaneado o texto plano): sin OCR no se pueden extraer sus requisitos.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias/{entidadId}/requisitos", dedupe: "una por documento (clave = id del documento)", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-revision.ts", nota: "se emite al subir un documento a la boveda cuyo texto no se pudo extraer (requires_ocr o failed); requiere la migracion 037" } },
  { id: "licitaciones.expediente.aprobacion_invalidada", ambito: "licitaciones", categoria: "aprobaciones", severidad: "atencion", roles: ["analyst"], icono: "ShieldAlert", titulo: "Se editó una sección y se invalidaron las aprobaciones vigentes", cuerpo: "El expediente debe aprobarse de nuevo, y no puede hacerlo quien editó la sección.", parametros: [], enlace: "/licitaciones/{orgSlug}/convocatorias/{entidadId}/propuesta-tecnica", dedupe: "una por seccion y version editada (clave = id de la propuesta + seccion + version)", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/licitaciones/avisos-revision.ts", nota: "se emite en PATCH .../proposal/sections/:sectionKey cuando el cambio de contenido invalido aprobaciones vigentes" } },
  // ---- Citas --------------------------------------------------------------------------------------
  { id: "citas.cita.nueva", ambito: "citas", categoria: "operacion", severidad: "info", roles: ["staff"], icono: "CalendarPlus", titulo: "Nueva cita agendada", cuerpo: null, parametros: [], enlace: "/citas/{orgSlug}/agenda", dedupe: "una por cita", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-citas/src/postgres-repository.ts" } },
  { id: "citas.cita.cancelada", ambito: "citas", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "CalendarX", titulo: "Un cliente canceló una cita", cuerpo: null, parametros: [], enlace: "/citas/{orgSlug}/agenda", dedupe: "una por cita cancelada", venceDias: 7, productor: { estado: "conectado", archivo: "packages/domain-citas/src/postgres-repository.ts" } },
  { id: "citas.recordatorio.fallido", ambito: "citas", categoria: "salud", severidad: "atencion", roles: [], icono: "BellOff", titulo: "Recordatorios de cita sin enviar", cuerpo: "Sin enviar: {cantidad}.", parametros: ["cantidad"], enlace: "/citas/{orgSlug}/mensajes-whatsapp", dedupe: "una por dia", venceDias: 5, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/citas/reminders.ts" } },
  { id: "citas.whatsapp.sin_plantilla", ambito: "citas", categoria: "salud", severidad: "atencion", roles: [], icono: "BellOff", titulo: "Avisos de WhatsApp sin plantilla aprobada", cuerpo: "No salieron por WhatsApp: {cantidad}. Aprueba la plantilla del evento para que lleguen fuera de las 24 horas; si el cliente dejó correo, se avisó por ahí.", parametros: ["cantidad"], enlace: "/citas/{orgSlug}/mensajes-whatsapp", dedupe: "una por organizacion por evento y dia", venceDias: 5, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/citas/reminders.ts" } },
  { id: "citas.escalacion.crisis", ambito: "citas", categoria: "agentes", severidad: "critica", roles: [], icono: "LifeBuoy", titulo: "Un cliente escribió un mensaje de crisis", cuerpo: "El agente respondió con el aviso de crisis y registró la escalación para tu seguimiento.", parametros: [], enlace: "/citas/{orgSlug}/avisos", dedupe: "una por escalacion (clave = id de la escalacion)", venceDias: 14, productor: { estado: "conectado", archivo: "packages/domain-citas/src/postgres-repository.ts" } },
  { id: "citas.escalacion.sin_seguimiento", ambito: "citas", categoria: "agentes", severidad: "critica", roles: [], icono: "Siren", titulo: "Escalaciones de crisis sin seguimiento", cuerpo: "Sin seguimiento: {cantidad}.", parametros: ["cantidad"], enlace: "/citas/{orgSlug}/avisos", dedupe: "una por dia", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/citas/avisos-ciclo.ts" } },
  { id: "citas.cita.por_confirmar", ambito: "citas", categoria: "operacion", severidad: "atencion", roles: ["staff"], icono: "CalendarClock", titulo: "Citas por confirmar en las próximas 48 horas", cuerpo: "Por confirmar: {cantidad}.", parametros: ["cantidad"], enlace: "/citas/{orgSlug}/avisos", dedupe: "una por dia", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/citas/avisos-ciclo.ts" } },
  { id: "citas.recordatorio.agotado", ambito: "citas", categoria: "salud", severidad: "atencion", roles: [], icono: "BellOff", titulo: "Recordatorios que no se pudieron entregar", cuerpo: "Agotaron sus reintentos: {cantidad}.", parametros: ["cantidad"], enlace: "/citas/{orgSlug}/avisos", dedupe: "una por cada recordatorio nuevo agotado (clave = instante del ultimo)", venceDias: 5, productor: { estado: "conectado", archivo: "apps/api/src/routes/verticals/citas/avisos-ciclo.ts" } },
  { id: "citas.conversacion.handoff", ambito: "citas", categoria: "agentes", severidad: "atencion", roles: ["staff"], icono: "UserRoundCog", titulo: "Un cliente necesita a una persona en WhatsApp", cuerpo: "El agente derivó una conversación: tómala desde Conversaciones.", parametros: [], enlace: "/citas/{orgSlug}/conversaciones", dedupe: "una por conversacion derivada (clave = id del handoff)", venceDias: 3, productor: { estado: "conectado", archivo: "packages/domain-citas/src/conversaciones/postgres-repository.ts", nota: "se emite cuando el agente pide una persona (hoy: una escalacion de crisis); en ese caso sube a severidad critica. Una toma iniciada por el propio personal no avisa" } },
  // ---- Superadmin (plataforma) --------------------------------------------------------------------
  { id: "superadmin.cfo.alerta", ambito: "superadmin", categoria: "cobranza", severidad: "critica", roles: [], icono: "ChartNoAxesCombined", titulo: "Alerta financiera de la plataforma", cuerpo: "Regla: {regla}. Organizaciones afectadas: {cantidad}.", parametros: ["regla", "cantidad"], enlace: "/superadmin/ejecutivo", dedupe: "una por regla por mes", venceDias: 31, productor: { estado: "conectado", archivo: "apps/api/src/routes/internal/superadmin-alertas-cfo.ts" } },
  { id: "superadmin.agente.fallo", ambito: "superadmin", categoria: "agentes", severidad: "critica", roles: [], icono: "Bot", titulo: "Un agente falló", cuerpo: "Agente: {agente}.", parametros: ["agente"], enlace: "/superadmin/agentes", dedupe: "una por agente por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/agentes/corridas.ts" } },
  { id: "superadmin.cron.fallo", ambito: "superadmin", categoria: "salud", severidad: "critica", roles: [], icono: "ServerCrash", titulo: "Un cron falló", cuerpo: "Tarea: {ruta}.", parametros: ["ruta"], enlace: "/superadmin", dedupe: "una por cron por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/salud/with-heartbeat.ts" } },
  { id: "superadmin.salud.cron_sin_latido", ambito: "superadmin", categoria: "salud", severidad: "critica", roles: [], icono: "ServerCrash", titulo: "Hay crons que nunca han corrido", cuerpo: "Crons de alta frecuencia sin ningún latido: {cantidad}. Revisa Salud operativa y la configuración de crons en Vercel.", parametros: ["cantidad"], enlace: "/superadmin/salud", dedupe: "una por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/salud/alerta-crons-sin-latido.ts", nota: "la emite el cron diario /internal/superadmin/resumen-diario cuando algun cron de cadencia <= 15 min no tiene ningun latido" } },
  { id: "superadmin.costo.ia_umbral", ambito: "superadmin", categoria: "cobranza", severidad: "atencion", roles: [], icono: "Gauge", titulo: "El gasto de IA superó un umbral", cuerpo: "Uso: {porcentaje} por ciento del presupuesto.", parametros: ["porcentaje"], enlace: "/superadmin/consumo-ia", dedupe: "una por umbral (80, 100) por mes", venceDias: 31, productor: { estado: "conectado", archivo: "apps/api/src/production/llm-usage-gateway-adapters.ts" } },
  { id: "superadmin.copiloto.tope_mensual", ambito: "superadmin", categoria: "cobranza", severidad: "atencion", roles: [], icono: "Gauge", titulo: "El Copiloto de superadmin usó {porcentaje} por ciento de su tope mensual", cuerpo: "Al llegar al 100 por ciento responde sin IA (las consultas directas siguen disponibles).", parametros: ["porcentaje"], enlace: "/superadmin/consumo-ia", dedupe: "una por umbral (80, 100) por mes", venceDias: 31, productor: { estado: "conectado", archivo: "apps/api/src/routes/superadmin-copiloto.ts", nota: "emite el umbral 80 y el 100 cuando el gasto del mes del Copiloto (bitacora y acumulador de la instancia) los alcanza; clave `<umbral>:<mes>`" } },
  { id: "superadmin.copiloto.accion_propuesta", ambito: "superadmin", categoria: "aprobaciones", severidad: "atencion", roles: [], icono: "UserRoundCheck", titulo: "El Copiloto propuso una acción que espera tu confirmación", cuerpo: "Revísala en Acciones; no se ejecuta sola y vence en pocos minutos.", parametros: [], enlace: "/superadmin/acciones", dedupe: "una por propuesta (clave = id del intent o nonce de la propuesta)", venceDias: 1, productor: { estado: "conectado", archivo: "apps/api/src/routes/superadmin-copiloto.ts", nota: "se emite al crear la propuesta con `proponer_accion` (apps/api/src/superadmin-copiloto/acciones.ts); sin PII: solo el tipo de aviso" } },
  { id: "superadmin.llm.fallback_alto", ambito: "superadmin", categoria: "salud", severidad: "atencion", roles: [], icono: "Shuffle", titulo: "Muchas llamadas de IA cayeron a un modelo de respaldo", cuerpo: "En la última hora, {porcentaje} por ciento de las llamadas usó un modelo de respaldo.", parametros: ["porcentaje"], enlace: "/superadmin/consumo-ia", dedupe: "una por hora", venceDias: 3, productor: { estado: "conectado", archivo: "apps/api/src/production/llm-usage-gateway-adapters.ts" } },
  { id: "superadmin.llm.modelo_caido", ambito: "superadmin", categoria: "salud", severidad: "critica", roles: [], icono: "TriangleAlert", titulo: "Un modelo de IA dejó de responder", cuerpo: "Modelo: {modelo}. El gateway pasa al siguiente modelo de la escalera.", parametros: ["modelo"], enlace: "/superadmin/salud", dedupe: "una por modelo por dia", venceDias: 7, productor: { estado: "conectado", archivo: "apps/api/src/production/llm-gateway.ts" } },
  { id: "superadmin.organizacion.onboarding_listo", ambito: "superadmin", categoria: "onboarding", severidad: "info", roles: [], icono: "CircleCheckBig", titulo: "Una organización terminó su onboarding", cuerpo: "Todos los pasos de su checklist están hechos. Revisa su ficha.", parametros: [], enlace: "/superadmin/organizaciones/{entidadId}", dedupe: "una por organizacion, para siempre (marcador persistente core.org_onboarding_aviso)", venceDias: 30, productor: { estado: "conectado", archivo: "apps/api/src/routes/internal/superadmin-mantenimiento.ts", nota: "el cron de mantenimiento llama a core.avisar_organizaciones_listas_for_system (0052), que marca el marcador persistente y devuelve las organizaciones a avisar, y emite una notificacion por cada una en la misma transaccion; nunca desde un GET" } },
  { id: "superadmin.organizacion.accion_pendiente", ambito: "superadmin", categoria: "aprobaciones", severidad: "atencion", roles: [], icono: "UserRoundCheck", titulo: "Una acción sobre una organización espera la aprobación de un segundo superadmin", cuerpo: null, parametros: [], enlace: "/superadmin/organizaciones?tab=gestion", dedupe: "una por solicitud", venceDias: 2, productor: { estado: "conectado", archivo: "apps/api/src/routes/superadmin-organizaciones.ts" } },
  { id: "superadmin.organizacion.miembro_aceptado", ambito: "superadmin", categoria: "onboarding", severidad: "info", roles: [], icono: "UserRoundCheck", titulo: "Una invitación de equipo fue aceptada", cuerpo: "Una persona invitada desde el back office ya tiene acceso a su organización. Revisa el equipo en su ficha.", parametros: [], enlace: "/superadmin/organizaciones/{entidadId}", dedupe: "una por invitacion", venceDias: 14, productor: { estado: "conectado", archivo: "apps/api/src/routes/superadmin-organizaciones-equipo.ts", nota: "POST /auth/accept-invite llama a core.superadmin_invite_acceptance_for_system (0053, solo sistema) y emite en su propia transaccion; solo para invitaciones creadas por un superadmin" } },
  ...EVENTOS_PLAN,
];

export function eventoPorId(id: string): EventoNotificacion | undefined {
  return CATALOGO_NOTIFICACIONES.find((e) => e.id === id);
}
