// @atiende/voice-core -- esqueleto de voz compartido por las verticales (LiveKit + Gemini Live, escalera Gemini -> cascada OpenRouter -> humano/buzon).
// Ver README.md: como una vertical monta su agente (perfil + registro de tools + guiones + repositorio).
export { CATALOGO_VOCES_GEMINI, VOZ_POR_DEFECTO, esVozDeGemini } from "./catalogo-voces.ts";
export type { VozCatalogoItem } from "./catalogo-voces.ts";
export * from "./types.ts";
export type { RepositorioKpiVoz, RepositorioLlamadasVoz } from "./repositorios.ts";
export { firmarPreviewToken, verificarPreviewToken, PREVIEW_TOKEN_TTL_MAX_SEGUNDOS, PREVIEW_TOKEN_TTL_POR_DEFECTO_SEGUNDOS } from "./preview-token.ts";
export type { PreviewTokenPayload, PreviewTokenEntrada, PreviewTokenVerificacion } from "./preview-token.ts";
export { redactarTranscripcion } from "./transcripcion.ts";
export { VozNoConfiguradaError, VozProveedorError } from "./provider.ts";
export type { VoiceAgentProvider, VozHerramientaDeclaracion, VozSalud, VozSesionPreviewEntrada, VozSesionPreviewProveedor } from "./provider.ts";
export { GeminiLiveProvider, GEMINI_LIVE_MODELO } from "./gemini-live-provider.ts";
export type { GeminiLiveProviderOptions } from "./gemini-live-provider.ts";
export { FakeVoiceProvider } from "./fake-voice-provider.ts";
export type { FakeVoiceProviderOptions } from "./fake-voice-provider.ts";
export * from "./kpi.ts";
export { CallStateMachine, LIMITES_POR_DEFECTO } from "./llamada/maquina.ts";
export type { AccionLlamada, EstadoLlamada, EventoLlamada, LimitesLlamada, MotivoEscalacionLlamada, ReglasCierreLlamada } from "./llamada/maquina.ts";
export { MENSAJE_IDS, mensajeSaludoRespaldo, saludoPorHora } from "./llamada/mensajes.ts";
export type { CatalogoMensajes, MensajeId, SaludoPorHora } from "./llamada/mensajes.ts";
export { evaluarInicioLlamada } from "./llamada/inicio.ts";
export type { DecisionInicio, EntradaInicioLlamada } from "./llamada/inicio.ts";
export { extraerTelefonoSipFrom } from "./llamada/sip.ts";
export type { CanonicalizarTelefono } from "./llamada/sip.ts";
export { eventoSinPII, redactarPII, referenciaLlamada } from "./llamada/log-sin-pii.ts";
export type { SumideroLog } from "./llamada/log-sin-pii.ts";
export { CABECERA_TURNO_LLAMADA, crearEjecutorTools, sanearArgumentos, transporteHttp } from "./llamada/ejecutor-tools.ts";
export type { ContextoEjecucionTool, EjecutorTools, EjecutorToolsOpciones, RegistroToolsVoz, ResultadoTool, ToolDefinicion, ToolJsonSchema, TransporteHttpOpciones, TransporteTools } from "./llamada/ejecutor-tools.ts";
export { ControladorLlamada } from "./llamada/controlador.ts";
export type { DecisionGuardiaCliente, DepsControlador, EventoKpiLlamada, GuardiaCliente, ResultadoLlamada, TurnoTranscrito } from "./llamada/controlador.ts";
export type { AbrirSesionLlamada, AperturaLlamada, ManejadoresSesion, ToolCallPedida, VozSesionLlamada } from "./llamada/sesion.ts";
export { GEMINI_LIVE_WS_URL, crearProveedorGeminiLlamada, declaracionesDeHerramientas, mensajeSetup } from "./llamada/gemini-live-sesion.ts";
export type { CrearSocketLive, GeminiLiveSesionOpciones, ProveedorGeminiLlamada, SocketLive } from "./llamada/gemini-live-sesion.ts";
export { ESCALERA_VOZ, VOZ_PLATAFORMA, costoEstimadoMicroUsd, precioPorMinutoMicroUsd } from "./config-plataforma.ts";
export type { ConfigPlataformaVoz, EscalonVoz } from "./config-plataforma.ts";
export { costoTotalMicroUsd, eventosCostoLlamada } from "./costo.ts";
export type { EntradaEventosCosto, EventoCostoUso, TramoLlamada } from "./costo.ts";
export { crearEscaleraLlamada } from "./escalera.ts";
export type { EscalonLlamada, EscaleraLlamada, OpcionesEscalera } from "./escalera.ts";
export { crearProveedorCascadaLlamada, energiaRms, pcm16AWav, pistaVocabulario } from "./llamada/cascada-openrouter.ts";
export type { CascadaOpenRouterOpciones, MensajeLlmVoz, PeticionLlmVoz, ProveedorCascadaLlamada, PuertoLlmVoz, RespuestaLlmVoz, ToolCallLlmVoz } from "./llamada/cascada-openrouter.ts";
export { crearEscalonesPlataforma, crearEscaleraPlataforma, estadoEscalera } from "./plataforma.ts";
export type { CredencialesVoz, DepsPlataformaVoz, EstadoEscaleraVoz, EstadoEscalonVoz } from "./plataforma.ts";
